// Copyright (c) LMCAD. Licensed under the MIT License.

//! WGSL codegen: string-build the distance function `lm_field(p)` from a
//! [`GpuNode`] tree.
//!
//! Every CPU distance formula is mirrored **branch-for-branch** (same guards,
//! same constants, same operation order) so the only CPU↔GPU differences are
//! per-operation rounding and the GPU's f32-only transcendentals — that is what
//! the declared tolerance `|gpu − cpu| ≤ 1e-4·(1 + |cpu|)` covers (enforced by
//! the parity suite, recorded in `NUMERICS.md`).
//!
//! Layout of the generated module:
//! - a static preamble of distance helpers (one per analytic primitive, the
//!   smooth/fillet/chamfer seam combinators, the cone-capsule strut, and the
//!   `Expr` runtime helpers);
//! - two scene storage buffers at `@group(0)`: the concatenated strut records
//!   of every lattice/pipe leaf, and the concatenated samples of every voxel
//!   grid leaf (always declared; bound to tiny dummies when unused);
//! - one `fn lm_n{K}(p: vec3f) -> f32` per tree node, emitted children-first
//!   (loops over struts / pattern copies live naturally in their node's
//!   function body), and the root wrapper `fn lm_field(p: vec3f) -> f32`.
//!
//! All scalar parameters are baked as WGSL literals via [`fmt_f32`]
//! (shortest-roundtrip formatting, so the shader parses back the identical f32
//! bits); strut and grid data travel as raw bytes, bit-exact.

use std::fmt::Write as _;
use std::sync::Arc;

use kernel_core::math::Vec3;
use kernel_implicit::expr_sdf::Expr;
use kernel_implicit::grid::VoxelGrid;

use crate::tree::GpuNode;
use crate::GpuError;

/// A lowered tree: the WGSL module source (everything up to, and including,
/// `lm_field`) plus the scene buffers it expects at `@group(0)`.
pub struct Lowered {
	/// WGSL source defining `fn lm_field(p: vec3f) -> f32` and its bindings.
	pub wgsl: String,
	/// Strut records `[ax, ay, az, ra, bx, by, bz, rb]` for every lattice/pipe
	/// leaf, in tree order — bind as `@group(0) @binding(0)`.
	pub struts: Vec<[f32; 8]>,
	/// Concatenated dense voxel-grid samples — bind as `@group(0) @binding(1)`.
	pub grid_data: Vec<f32>,
}

/// Static WGSL helpers mirroring the CPU formulas (see module docs).
const PREAMBLE: &str = r#"// Generated by lmcad kernel-gpu — do not edit.
struct LmStrut { a_ra: vec4f, b_rb: vec4f }
@group(0) @binding(0) var<storage, read> lm_struts: array<LmStrut>;
@group(0) @binding(1) var<storage, read> lm_grid: array<f32>;

// ops.rs::smin — polynomial smooth minimum, hard min for k <= 0.
fn lm_smin(a: f32, b: f32, k: f32) -> f32 {
	if (k <= 0.0) { return min(a, b); }
	let h = clamp(0.5 + 0.5 * (b - a) / k, 0.0, 1.0);
	return (b + h * (a - b)) - k * h * (1.0 - h);
}
fn lm_smax(a: f32, b: f32, k: f32) -> f32 { return -lm_smin(-a, -b, k); }

// features.rs::fillet_union_dist / chamfer_union_dist.
fn lm_fillet(da: f32, db: f32, r: f32) -> f32 {
	if (r <= 0.0) { return min(da, db); }
	let ux = max(r - da, 0.0);
	let uy = max(r - db, 0.0);
	return max(r, min(da, db)) - sqrt(ux * ux + uy * uy);
}
fn lm_chamfer(da: f32, db: f32, r: f32) -> f32 {
	let hard = min(da, db);
	if (r <= 0.0) { return hard; }
	return min(hard, (da + db - r) * 0.70710678);
}

// primitives.rs distance formulas, branch-for-branch.
fn lm_sd_sphere(p: vec3f, c: vec3f, r: f32) -> f32 { return length(p - c) - r; }
fn lm_sd_cuboid(p: vec3f, c: vec3f, h: vec3f) -> f32 {
	let q = abs(p - c) - h;
	return length(max(q, vec3f(0.0))) + min(max(q.x, max(q.y, q.z)), 0.0);
}
fn lm_sd_cylinder(p: vec3f, ca: vec3f, cb: vec3f, r: f32) -> f32 {
	let ba = cb - ca;
	let pa = p - ca;
	let baba = dot(ba, ba);
	if (baba < 1e-12) { return length(pa) - r; }
	let paba = dot(pa, ba);
	let x = length(pa * baba - ba * paba) - r * baba;
	let y = abs(paba - baba * 0.5) - baba * 0.5;
	let x2 = x * x;
	let y2 = y * y * baba;
	var d: f32;
	if (max(x, y) < 0.0) {
		d = -min(x2, y2);
	} else {
		d = select(0.0, x2, x > 0.0) + select(0.0, y2, y > 0.0);
	}
	return sign(d) * sqrt(abs(d)) / baba;
}
fn lm_sd_cone(p: vec3f, ca: vec3f, cb: vec3f, ra: f32, rb: f32) -> f32 {
	let rba = rb - ra;
	let ba = cb - ca;
	let baba = dot(ba, ba);
	if (baba < 1e-12) { return length(p - ca) - ra; }
	let pa = p - ca;
	let papa = dot(pa, pa);
	let paba = dot(pa, ba) / baba;
	let x = sqrt(max(papa - paba * paba * baba, 0.0));
	var cax: f32;
	if (paba < 0.5) { cax = max(x - ra, 0.0); } else { cax = max(x - rb, 0.0); }
	let cay = abs(paba - 0.5) - 0.5;
	let k = rba * rba + baba;
	let f = clamp((rba * (x - ra) + paba * baba) / k, 0.0, 1.0);
	let cbx = x - ra - f * rba;
	let cby = paba - f;
	var s = 1.0;
	if (cbx < 0.0 && cay < 0.0) { s = -1.0; }
	return s * sqrt(min(cax * cax + cay * cay * baba, cbx * cbx + cby * cby * baba));
}
fn lm_sd_torus(p: vec3f, c: vec3f, n: vec3f, major: f32, minor: f32) -> f32 {
	let pl = p - c;
	let axial = dot(pl, n);
	let radial = length(pl - n * axial);
	let qx = radial - major;
	return sqrt(qx * qx + axial * axial) - minor;
}
fn lm_sd_capsule(p: vec3f, ca: vec3f, cb: vec3f, r: f32) -> f32 {
	let pa = p - ca;
	let ba = cb - ca;
	let baba = dot(ba, ba);
	if (baba < 1e-12) { return length(pa) - r; }
	let h = clamp(dot(pa, ba) / baba, 0.0, 1.0);
	return length(pa - ba * h) - r;
}

// lattice.rs::Strut::distance — Quilez round cone, branch-for-branch.
fn lm_sd_strut(p: vec3f, st: LmStrut) -> f32 {
	let a = st.a_ra.xyz;
	let ra = st.a_ra.w;
	let b = st.b_rb.xyz;
	let rb = st.b_rb.w;
	let ba = b - a;
	let l2 = dot(ba, ba);
	let rr = ra - rb;
	let a2 = l2 - rr * rr;
	if (a2 <= 0.0 || l2 < 1e-12) {
		if (ra >= rb) { return length(p - a) - ra; }
		return length(p - b) - rb;
	}
	let il2 = 1.0 / l2;
	let pa = p - a;
	let y = dot(pa, ba);
	let z = y - l2;
	let dv = pa * l2 - ba * y;
	let x2 = dot(dv, dv);
	let y2 = y * y * l2;
	let z2 = z * z * l2;
	let k = sign(rr) * rr * rr * x2;
	if (sign(z) * a2 * z2 > k) { return sqrt(x2 + z2) * il2 - rb; }
	if (sign(y) * a2 * y2 < k) { return sqrt(x2 + y2) * il2 - ra; }
	return (sqrt(x2 * a2 * il2) + y * rr) * il2 - ra;
}

// expr_sdf.rs::Expr runtime helpers (f32 on the GPU; CPU evaluates f64).
fn lm_rem_euclid(a: f32, m: f32) -> f32 {
	let r = a % m;
	if (r < 0.0) { return r + abs(m); }
	return r;
}
fn lm_len2(a: f32, b: f32) -> f32 { return sqrt(a * a + b * b); }
fn lm_len3(a: f32, b: f32, c: f32) -> f32 { return sqrt(a * a + b * b + c * c); }
"#;

/// Format a finite `f32` as a WGSL literal whose parse recovers the identical
/// bits (Rust's `{:?}` is shortest-roundtrip; WGSL converts decimal literals to
/// the nearest f32). Non-finite values cannot be WGSL literals — loud error.
fn fmt_f32(v: f32, what: &str) -> Result<String, GpuError> {
	if !v.is_finite() {
		return Err(GpuError::Lower(format!("{what}: non-finite parameter {v} cannot be lowered to WGSL")));
	}
	// `{:?}` always includes a `.0` or exponent for floats, but be explicit
	// about the f32 type with the `f` suffix to keep WGSL inference local.
	Ok(format!("{v:?}f"))
}

/// Format a `Vec3` as a `vec3f(..)` literal (each lane shortest-roundtrip).
fn fmt_vec3(v: Vec3, what: &str) -> Result<String, GpuError> {
	Ok(format!("vec3f({}, {}, {})", fmt_f32(v.x, what)?, fmt_f32(v.y, what)?, fmt_f32(v.z, what)?))
}

/// Lower an [`Expr`] to a WGSL expression over `p.x/p.y/p.z`. Constants are
/// narrowed to f32 (the GPU's evaluation precision — documented on
/// [`GpuNode::Expr`]). The tree shape maps 1:1, so each sub-expression is
/// evaluated exactly once (helpers take the operands as arguments).
fn expr_wgsl(e: &Expr) -> Result<String, GpuError> {
	Ok(match e {
		Expr::X => "p.x".to_string(),
		Expr::Y => "p.y".to_string(),
		Expr::Z => "p.z".to_string(),
		Expr::Const(c) => fmt_f32(*c as f32, "Expr::Const")?,
		Expr::Add(a, b) => format!("({} + {})", expr_wgsl(a)?, expr_wgsl(b)?),
		Expr::Sub(a, b) => format!("({} - {})", expr_wgsl(a)?, expr_wgsl(b)?),
		Expr::Mul(a, b) => format!("({} * {})", expr_wgsl(a)?, expr_wgsl(b)?),
		Expr::Div(a, b) => format!("({} / {})", expr_wgsl(a)?, expr_wgsl(b)?),
		Expr::Min(a, b) => format!("min({}, {})", expr_wgsl(a)?, expr_wgsl(b)?),
		Expr::Max(a, b) => format!("max({}, {})", expr_wgsl(a)?, expr_wgsl(b)?),
		Expr::Neg(a) => format!("(-({}))", expr_wgsl(a)?),
		Expr::Abs(a) => format!("abs({})", expr_wgsl(a)?),
		Expr::Sqrt(a) => format!("sqrt({})", expr_wgsl(a)?),
		Expr::Sin(a) => format!("sin({})", expr_wgsl(a)?),
		Expr::Cos(a) => format!("cos({})", expr_wgsl(a)?),
		Expr::Atan2 { y, x } => format!("atan2({}, {})", expr_wgsl(y)?, expr_wgsl(x)?),
		Expr::Mod(a, m) => format!("lm_rem_euclid({}, {})", expr_wgsl(a)?, expr_wgsl(m)?),
		// CPU: value.max(lo).min(hi) — non-panicking even for lo > hi.
		Expr::Clamp { value, lo, hi } => format!("min(max({}, {}), {})", expr_wgsl(value)?, expr_wgsl(lo)?, expr_wgsl(hi)?),
		Expr::Length2(a, b) => format!("lm_len2({}, {})", expr_wgsl(a)?, expr_wgsl(b)?),
		Expr::Length3(a, b, c) => format!("lm_len3({}, {}, {})", expr_wgsl(a)?, expr_wgsl(b)?, expr_wgsl(c)?),
	})
}

struct Codegen {
	fns: String,
	struts: Vec<[f32; 8]>,
	grid: Vec<f32>,
	next: usize,
}

impl Codegen {
	/// Reserve the next function name (`lm_n{K}`).
	fn name(&mut self) -> String {
		let n = format!("lm_n{}", self.next);
		self.next += 1;
		n
	}

	/// Emit one `fn {name}(p: vec3f) -> f32 {{ body }}`.
	fn push_fn(&mut self, name: &str, body: &str) {
		let _ = write!(self.fns, "fn {name}(p: vec3f) -> f32 {{\n{body}}}\n");
	}

	/// Append strut records, returning their `[start, end)` buffer range.
	fn push_struts(&mut self, records: impl Iterator<Item = [f32; 8]>) -> (u32, u32) {
		let start = self.struts.len() as u32;
		self.struts.extend(records);
		(start, self.struts.len() as u32)
	}

	/// A strut-loop leaf body (`min` over `lm_struts[start..end)` — the exact
	/// brute-force field the CPU's grid acceleration reproduces). The 1e30 seed
	/// is dead as soon as one strut exists (lowering rejects empty leaves), so
	/// it never appears in results.
	fn strut_leaf(&mut self, start: u32, end: u32) -> String {
		let name = self.name();
		self.push_fn(
			&name,
			&format!(
				"\tvar d = 1e30f;\n\tfor (var i = {start}u; i < {end}u; i++) {{\n\t\td = min(d, lm_sd_strut(p, lm_struts[i]));\n\t}}\n\treturn d;\n"
			),
		);
		name
	}

	/// A dense voxel-grid leaf: trilinear interpolation mirroring
	/// `grid.rs::VoxelGrid::distance` (clamp into the lattice, sample the 8
	/// cell corners, trilerp, add the exterior gap).
	fn grid_leaf(&mut self, g: &Arc<VoxelGrid>) -> Result<String, GpuError> {
		let [nx, ny, nz] = g.dims;
		if g.data.len() != nx * ny * nz {
			return Err(GpuError::Lower(format!(
				"VoxelGrid leaf: data length {} does not match dims {:?}",
				g.data.len(),
				g.dims
			)));
		}
		if nx < 2 || ny < 2 || nz < 2 {
			// CPU: degenerate grids return the first sample (or +inf when empty).
			// +inf has no WGSL literal — reject the empty case loudly.
			let v = g.data.first().copied().unwrap_or(f32::INFINITY);
			let lit = fmt_f32(v, "VoxelGrid leaf: degenerate grid value")?;
			let name = self.name();
			self.push_fn(&name, &format!("\treturn {lit};\n"));
			return Ok(name);
		}
		let base = self.grid.len() as u32;
		self.grid.extend_from_slice(&g.data);
		let hi = g.point(nx - 1, ny - 1, nz - 1);
		let what = "VoxelGrid leaf";
		let lo = fmt_vec3(g.origin, what)?;
		let hi = fmt_vec3(hi, what)?;
		let vs = fmt_f32(g.voxel_size, what)?;
		let (nxw, nxyw) = (nx as u32, (nx * ny) as u32);
		let (im, jm, km) = ((nx - 2) as u32, (ny - 2) as u32, (nz - 2) as u32);
		let name = self.name();
		let body = format!(
			"\tlet lo = {lo};\n\
			 \tlet hi = {hi};\n\
			 \tlet q = clamp(p, lo, hi);\n\
			 \tlet l = (q - lo) / {vs};\n\
			 \tlet i = min(u32(floor(l.x)), {im}u);\n\
			 \tlet j = min(u32(floor(l.y)), {jm}u);\n\
			 \tlet k = min(u32(floor(l.z)), {km}u);\n\
			 \tlet f = l - vec3f(f32(i), f32(j), f32(k));\n\
			 \tlet base = {base}u + i + {nxw}u * j + {nxyw}u * k;\n\
			 \tlet c000 = lm_grid[base];\n\
			 \tlet c100 = lm_grid[base + 1u];\n\
			 \tlet c010 = lm_grid[base + {nxw}u];\n\
			 \tlet c110 = lm_grid[base + {nxw}u + 1u];\n\
			 \tlet c001 = lm_grid[base + {nxyw}u];\n\
			 \tlet c101 = lm_grid[base + {nxyw}u + 1u];\n\
			 \tlet c011 = lm_grid[base + {nxyw}u + {nxw}u];\n\
			 \tlet c111 = lm_grid[base + {nxyw}u + {nxw}u + 1u];\n\
			 \tlet c00 = c000 * (1.0 - f.x) + c100 * f.x;\n\
			 \tlet c10 = c010 * (1.0 - f.x) + c110 * f.x;\n\
			 \tlet c01 = c001 * (1.0 - f.x) + c101 * f.x;\n\
			 \tlet c11 = c011 * (1.0 - f.x) + c111 * f.x;\n\
			 \tlet c0 = c00 * (1.0 - f.y) + c10 * f.y;\n\
			 \tlet c1 = c01 * (1.0 - f.y) + c11 * f.y;\n\
			 \treturn c0 * (1.0 - f.z) + c1 * f.z + length(p - q);\n"
		);
		self.push_fn(&name, &body);
		Ok(name)
	}

	/// Emit the function for `node`, returning its name. Children first.
	fn emit(&mut self, node: &GpuNode) -> Result<String, GpuError> {
		match node {
			GpuNode::Sphere { center, radius } => {
				let (c, r) = (fmt_vec3(*center, "Sphere")?, fmt_f32(*radius, "Sphere")?);
				let name = self.name();
				self.push_fn(&name, &format!("\treturn lm_sd_sphere(p, {c}, {r});\n"));
				Ok(name)
			}
			GpuNode::Cuboid { center, half } => {
				let (c, h) = (fmt_vec3(*center, "Cuboid")?, fmt_vec3(*half, "Cuboid")?);
				let name = self.name();
				self.push_fn(&name, &format!("\treturn lm_sd_cuboid(p, {c}, {h});\n"));
				Ok(name)
			}
			GpuNode::Cylinder { a, b, radius } => {
				let (a, b, r) = (fmt_vec3(*a, "Cylinder")?, fmt_vec3(*b, "Cylinder")?, fmt_f32(*radius, "Cylinder")?);
				let name = self.name();
				self.push_fn(&name, &format!("\treturn lm_sd_cylinder(p, {a}, {b}, {r});\n"));
				Ok(name)
			}
			GpuNode::Cone { a, b, ra, rb } => {
				let (a, b) = (fmt_vec3(*a, "Cone")?, fmt_vec3(*b, "Cone")?);
				let (ra, rb) = (fmt_f32(*ra, "Cone")?, fmt_f32(*rb, "Cone")?);
				let name = self.name();
				self.push_fn(&name, &format!("\treturn lm_sd_cone(p, {a}, {b}, {ra}, {rb});\n"));
				Ok(name)
			}
			GpuNode::Plane { point, normal } => {
				// Mirror Plane::new: bake the unit normal and offset in host f32.
				let n = normal.normalize_or_zero();
				let o = point.dot(n);
				let (n, o) = (fmt_vec3(n, "Plane")?, fmt_f32(o, "Plane")?);
				let name = self.name();
				self.push_fn(&name, &format!("\treturn dot(p, {n}) - {o};\n"));
				Ok(name)
			}
			GpuNode::Torus { center, axis, major, minor } => {
				// CPU normalizes the axis per query in f32; baking the host f32
				// normalization yields the identical unit vector bits.
				let n = axis.normalize_or_zero();
				let (c, n) = (fmt_vec3(*center, "Torus")?, fmt_vec3(n, "Torus")?);
				let (ma, mi) = (fmt_f32(*major, "Torus")?, fmt_f32(*minor, "Torus")?);
				let name = self.name();
				self.push_fn(&name, &format!("\treturn lm_sd_torus(p, {c}, {n}, {ma}, {mi});\n"));
				Ok(name)
			}
			GpuNode::Capsule { a, b, radius } => {
				let (a, b, r) = (fmt_vec3(*a, "Capsule")?, fmt_vec3(*b, "Capsule")?, fmt_f32(*radius, "Capsule")?);
				let name = self.name();
				self.push_fn(&name, &format!("\treturn lm_sd_capsule(p, {a}, {b}, {r});\n"));
				Ok(name)
			}
			GpuNode::Gyroid { scale, thickness, .. } => {
				let name = self.name();
				if scale.abs() < 1e-12 {
					// CPU guard: zero frequency is a constant field, not NaN.
					let t = fmt_f32(-thickness, "Gyroid")?;
					self.push_fn(&name, &format!("\treturn {t};\n"));
				} else {
					let s = fmt_f32(*scale, "Gyroid")?;
					let t = fmt_f32(*thickness, "Gyroid")?;
					// Mirror the CPU's `/ sqrt(3)` (host-computed f32 sqrt —
					// identical bits to the CPU's runtime constant).
					let sqrt3 = fmt_f32(3.0f32.sqrt(), "Gyroid")?;
					self.push_fn(
						&name,
						&format!(
							"\tlet q = p * {s};\n\tlet g = sin(q.x) * cos(q.y) + sin(q.y) * cos(q.z) + sin(q.z) * cos(q.x);\n\treturn (abs(g) / {s} - {t}) / {sqrt3};\n"
						),
					);
				}
				Ok(name)
			}
			GpuNode::Lattice { nodes, struts } => {
				if struts.is_empty() {
					// CPU yields an empty solid (distance +inf) — +inf is not
					// expressible in WGSL, and an all-empty lattice on the GPU
					// preview path is a modelling error anyway. Loud refusal.
					return Err(GpuError::Lower("BeamLattice leaf with zero struts cannot be lowered (CPU distance is +inf)".into()));
				}
				for n in nodes {
					if !n.is_finite() {
						return Err(GpuError::Lower("BeamLattice leaf: non-finite node position".into()));
					}
				}
				let mut records = Vec::with_capacity(struts.len());
				for &(ia, ib, ra, rb) in struts {
					let (ia, ib) = (ia as usize, ib as usize);
					if ia >= nodes.len() || ib >= nodes.len() {
						return Err(GpuError::Lower(format!(
							"BeamLattice leaf: strut ({ia}, {ib}) references a node out of range (have {})",
							nodes.len()
						)));
					}
					if !(ra > 0.0 && rb > 0.0 && ra.is_finite() && rb.is_finite()) {
						return Err(GpuError::Lower(format!("BeamLattice leaf: non-positive or non-finite strut radius ({ra}, {rb})")));
					}
					let (a, b) = (nodes[ia], nodes[ib]);
					records.push([a.x, a.y, a.z, ra, b.x, b.y, b.z, rb]);
				}
				let (start, end) = self.push_struts(records.into_iter());
				Ok(self.strut_leaf(start, end))
			}
			GpuNode::Pipe { path, radii } => {
				if path.len() < 2 || path.len() != radii.len() {
					return Err(GpuError::Lower(format!(
						"Pipe leaf: need >= 2 path points with one radius each (got {} points, {} radii)",
						path.len(),
						radii.len()
					)));
				}
				if !path.iter().all(|p| p.is_finite()) || !radii.iter().all(|r| *r > 0.0 && r.is_finite()) {
					return Err(GpuError::Lower("Pipe leaf: non-finite path point or non-positive radius".into()));
				}
				let records = path
					.windows(2)
					.zip(radii.windows(2))
					.map(|(p, r)| [p[0].x, p[0].y, p[0].z, r[0], p[1].x, p[1].y, p[1].z, r[1]])
					.collect::<Vec<_>>();
				let (start, end) = self.push_struts(records.into_iter());
				Ok(self.strut_leaf(start, end))
			}
			GpuNode::Grid(g) => self.grid_leaf(g),
			GpuNode::Expr { expr, lipschitz, .. } => {
				if !(lipschitz.is_finite() && *lipschitz > 0.0) {
					return Err(GpuError::Lower(format!("ExprSdf leaf: lipschitz_bound must be finite and > 0, got {lipschitz}")));
				}
				// CPU stores 1/L in f64 and narrows the product; bake the f64
				// reciprocal narrowed to f32.
				let invl = fmt_f32((1.0 / lipschitz) as f32, "ExprSdf")?;
				let e = expr_wgsl(expr)?;
				let name = self.name();
				self.push_fn(&name, &format!("\treturn ({e}) * {invl};\n"));
				Ok(name)
			}
			GpuNode::Union(a, b) => self.binary(a, b, |fa, fb| format!("\treturn min({fa}(p), {fb}(p));\n")),
			GpuNode::Intersection(a, b) => self.binary(a, b, |fa, fb| format!("\treturn max({fa}(p), {fb}(p));\n")),
			GpuNode::Difference(a, b) => self.binary(a, b, |fa, fb| format!("\treturn max({fa}(p), -{fb}(p));\n")),
			GpuNode::SmoothUnion(a, b, k) => {
				let k = fmt_f32(*k, "SmoothUnion")?;
				self.binary(a, b, move |fa, fb| format!("\treturn lm_smin({fa}(p), {fb}(p), {k});\n"))
			}
			GpuNode::SmoothIntersection(a, b, k) => {
				let k = fmt_f32(*k, "SmoothIntersection")?;
				self.binary(a, b, move |fa, fb| format!("\treturn lm_smax({fa}(p), {fb}(p), {k});\n"))
			}
			GpuNode::SmoothDifference(a, b, k) => {
				let k = fmt_f32(*k, "SmoothDifference")?;
				self.binary(a, b, move |fa, fb| format!("\treturn lm_smax({fa}(p), -{fb}(p), {k});\n"))
			}
			GpuNode::Offset(a, t) => {
				let t = fmt_f32(*t, "Offset")?;
				self.unary(a, move |fa| format!("\treturn {fa}(p) - {t};\n"))
			}
			GpuNode::Shell(a, t) => {
				let t = fmt_f32(*t, "Shell")?;
				self.unary(a, move |fa| format!("\treturn abs({fa}(p)) - {t};\n"))
			}
			GpuNode::Transform(a, fwd) => {
				// Mirror ops.rs::Xform::new — inverse for sampling, the x-basis
				// length as the uniform scale factor.
				let inv = fwd.inverse();
				let scale = fwd.matrix3.x_axis.length();
				let what = "Transform";
				let (cx, cy, cz) = (
					fmt_vec3(inv.matrix3.x_axis.into(), what)?,
					fmt_vec3(inv.matrix3.y_axis.into(), what)?,
					fmt_vec3(inv.matrix3.z_axis.into(), what)?,
				);
				let t = fmt_vec3(inv.translation.into(), what)?;
				let s = fmt_f32(scale, what)?;
				self.unary(a, move |fa| {
					format!("\tlet q = mat3x3f({cx}, {cy}, {cz}) * p + {t};\n\treturn {s} * {fa}(q);\n")
				})
			}
			GpuNode::LinearArray(a, step, count) => {
				let st = fmt_vec3(*step, "LinearArray")?;
				let count = (*count).max(1);
				self.unary(a, move |fa| {
					format!(
						"\tvar d = 1e30f;\n\tfor (var i = 0u; i < {count}u; i++) {{\n\t\td = min(d, {fa}(p - {st} * f32(i)));\n\t}}\n\treturn d;\n"
					)
				})
			}
			GpuNode::PolarArray(a, center, axis, count, ang) => {
				// CPU rotates by Quat::from_axis_angle(axis, -ang*i); Rodrigues
				// about the same unit axis is the identical rotation (rounding
				// differences are covered by the declared tolerance).
				let c = fmt_vec3(*center, "PolarArray")?;
				let ax = fmt_vec3(*axis, "PolarArray")?;
				let ang = fmt_f32(*ang, "PolarArray")?;
				let count = (*count).max(1);
				self.unary(a, move |fa| {
					format!(
						"\tvar d = 1e30f;\n\
						 \tfor (var i = 0u; i < {count}u; i++) {{\n\
						 \t\tlet ang = -{ang} * f32(i);\n\
						 \t\tlet cs = cos(ang);\n\
						 \t\tlet sn = sin(ang);\n\
						 \t\tlet v = p - {c};\n\
						 \t\tlet q = v * cs + cross({ax}, v) * sn + {ax} * (dot({ax}, v) * (1.0 - cs));\n\
						 \t\td = min(d, {fa}({c} + q));\n\
						 \t}}\n\
						 \treturn d;\n"
					)
				})
			}
			GpuNode::Mirror(a, point, normal) => {
				let pt = fmt_vec3(*point, "Mirror")?;
				let n = fmt_vec3(*normal, "Mirror")?;
				self.unary(a, move |fa| {
					format!("\tlet refl = p - {n} * (2.0 * dot(p - {pt}, {n}));\n\treturn min({fa}(p), {fa}(refl));\n")
				})
			}
			GpuNode::OffsetBy(a, field, max_abs) => {
				let m = fmt_f32(*max_abs, "OffsetBy")?;
				let e = expr_wgsl(field)?;
				self.unary(a, move |fa| {
					format!("\tlet w = min(max({e}, -{m}), {m});\n\treturn {fa}(p) - w;\n")
				})
			}
			GpuNode::LerpBlend(a, b, field) => {
				let e = expr_wgsl(field)?;
				self.binary(a, b, move |fa, fb| {
					format!("\tlet w = min(max({e}, 0.0), 1.0);\n\treturn {fa}(p) * (1.0 - w) + {fb}(p) * w;\n")
				})
			}
			GpuNode::FilletUnion(a, b, r) => {
				let r = fmt_f32(*r, "FilletUnion")?;
				self.binary(a, b, move |fa, fb| format!("\treturn lm_fillet({fa}(p), {fb}(p), {r});\n"))
			}
			GpuNode::ChamferUnion(a, b, r) => {
				let r = fmt_f32(*r, "ChamferUnion")?;
				self.binary(a, b, move |fa, fb| format!("\treturn lm_chamfer({fa}(p), {fb}(p), {r});\n"))
			}
			// Difference variants mirror features.rs::Feature::combine —
			// `-seam(-da, db)` keeps the treatment on the cut edge.
			GpuNode::FilletDifference(a, b, r) => {
				let r = fmt_f32(*r, "FilletDifference")?;
				self.binary(a, b, move |fa, fb| format!("\treturn -lm_fillet(-{fa}(p), {fb}(p), {r});\n"))
			}
			GpuNode::ChamferDifference(a, b, r) => {
				let r = fmt_f32(*r, "ChamferDifference")?;
				self.binary(a, b, move |fa, fb| format!("\treturn -lm_chamfer(-{fa}(p), {fb}(p), {r});\n"))
			}
		}
	}

	fn unary(&mut self, a: &GpuNode, body: impl FnOnce(&str) -> String) -> Result<String, GpuError> {
		let fa = self.emit(a)?;
		let name = self.name();
		self.push_fn(&name, &body(&fa));
		Ok(name)
	}

	fn binary(&mut self, a: &GpuNode, b: &GpuNode, body: impl FnOnce(&str, &str) -> String) -> Result<String, GpuError> {
		let fa = self.emit(a)?;
		let fb = self.emit(b)?;
		let name = self.name();
		self.push_fn(&name, &body(&fa, &fb));
		Ok(name)
	}
}

/// Lower a tree to its WGSL field module and scene buffers.
pub fn lower(tree: &GpuNode) -> Result<Lowered, GpuError> {
	let mut cg = Codegen { fns: String::new(), struts: Vec::new(), grid: Vec::new(), next: 0 };
	let root = cg.emit(tree)?;
	let mut wgsl = String::with_capacity(PREAMBLE.len() + cg.fns.len() + 64);
	wgsl.push_str(PREAMBLE);
	wgsl.push_str(&cg.fns);
	let _ = write!(wgsl, "fn lm_field(p: vec3f) -> f32 {{\n\treturn {root}(p);\n}}\n");
	Ok(Lowered { wgsl, struts: cg.struts, grid_data: cg.grid })
}
