[package]
name = "kernel-model"
edition = "2021"
version = "0.1.0"
license = "MIT"
authors = ["LMCAD"]

[dependencies]
kernel-core = { path = "../kernel-core" }
kernel-implicit = { path = "../kernel-implicit" }
kernel-brep = { path = "../kernel-brep" }
serde = { workspace = true }
serde_json = { workspace = true }
