//! Self-describing op surface (M3 Discovery). The op catalogue AND the per-op parameter table
//! are derived from the [`OpKind`] enum: `op_tag` through a **compile-forced exhaustive match**
//! (adding a variant without regenerating fails to compile), [`OP_NAMES`]/[`OP_PARAMS`] as
//! generated tables pinned to it by `tests/describe.rs`. Regenerate this WHOLE file with
//! `python3 tools/gen_discover.py` whenever `program.rs`'s `OpKind` changes — never hand-edit.

use crate::program::OpKind;

/// Canonical wire tag of an op — matches serde's `rename_all = "snake_case"` plus every explicit
/// `#[serde(rename)]`. The match is EXHAUSTIVE (the compiler forces one arm per variant); that is
/// the anti-drift guarantee behind [`OP_NAMES`] and the `describe` op.
pub fn op_tag(op: &OpKind) -> &'static str {
	match op {
		OpKind::Box { .. } => "box",
		OpKind::Cylinder { .. } => "cylinder",
		OpKind::Sphere { .. } => "sphere",
		OpKind::Cone { .. } => "cone",
		OpKind::Torus { .. } => "torus",
		OpKind::Extrude { .. } => "extrude",
		OpKind::ExtrudeWithHoles { .. } => "extrude_with_holes",
		OpKind::ExtrudeTapered { .. } => "extrude_tapered",
		OpKind::Revolve { .. } => "revolve",
		OpKind::Loft { .. } => "loft",
		OpKind::Sweep { .. } => "sweep",
		OpKind::Sketch { .. } => "sketch",
		OpKind::SketchExtrude { .. } => "sketch_extrude",
		OpKind::SketchRevolve { .. } => "sketch_revolve",
		OpKind::Union { .. } => "union",
		OpKind::Difference { .. } => "difference",
		OpKind::Intersection { .. } => "intersection",
		OpKind::UnionAll { .. } => "union_all",
		OpKind::FilletEdgeNear { .. } => "fillet_edge_near",
		OpKind::ChamferEdgeNear { .. } => "chamfer_edge_near",
		OpKind::FilletCircularRim { .. } => "fillet_circular_rim",
		OpKind::Translate { .. } => "translate",
		OpKind::RotateZ { .. } => "rotate_z",
		OpKind::RotateX { .. } => "rotate_x",
		OpKind::RotateY { .. } => "rotate_y",
		OpKind::Pose { .. } => "pose",
		OpKind::Mirror { .. } => "mirror",
		OpKind::LinearPattern { .. } => "linear_pattern",
		OpKind::PolarPattern { .. } => "polar_pattern",
		OpKind::Validate { .. } => "validate",
		OpKind::Volume { .. } => "volume",
		OpKind::ExactVolume { .. } => "exact_volume",
		OpKind::MassProperties { .. } => "mass_properties",
		OpKind::BoundingBox { .. } => "bounding_box",
		OpKind::WallThickness { .. } => "wall_thickness",
		OpKind::DraftAnalysis { .. } => "draft_analysis",
		OpKind::Assert { .. } => "assert",
		OpKind::AssertDisjoint { .. } => "assert_disjoint",
		OpKind::CoincidentFit { .. } => "coincident_fit",
		OpKind::SupportReport { .. } => "support_report",
		OpKind::Clearance { .. } => "clearance",
		OpKind::Describe { .. } => "describe",
		OpKind::ListFaces { .. } => "list_faces",
		OpKind::ListEdges { .. } => "list_edges",
		OpKind::ExportStl { .. } => "export_stl",
		OpKind::ExportStep { .. } => "export_step",
		OpKind::Export3mf { .. } => "export_3mf",
		OpKind::GyroidBlock { .. } => "gyroid_block",
		OpKind::MeasureDimension { .. } => "measure_dimension",
		OpKind::Tpms { .. } => "tpms",
		OpKind::HybridBoolean { .. } => "hybrid_boolean",
		OpKind::Implicit { .. } => "implicit",
		OpKind::Shell { .. } => "shell",
		OpKind::OffsetSolid { .. } => "offset_solid",
		OpKind::ShellSolid { .. } => "shell_solid",
		OpKind::SolidFromImplicit { .. } => "solid_from_implicit",
		OpKind::ThinWall { .. } => "thin_wall",
		OpKind::MinLigament { .. } => "min_ligament",
		OpKind::SampleDensityGrid { .. } => "sample_density_grid",
		OpKind::MeshDensityGrid { .. } => "mesh_density_grid",
		OpKind::LoadPart { .. } => "load_part",
		OpKind::ImportStep { .. } => "import_step",
		OpKind::ImportMesh { .. } => "import_mesh",
		OpKind::MeshCarve { .. } => "mesh_carve",
		OpKind::LibraryAdd { .. } => "library_add",
		OpKind::LibrarySearch { .. } => "library_search",
		OpKind::LibraryInstantiate { .. } => "library_instantiate",
		OpKind::LibraryDeprecate { .. } => "library_deprecate",
		OpKind::LibraryRemove { .. } => "library_remove",
		OpKind::SpurGear { .. } => "spur_gear",
		OpKind::HexBolt { .. } => "hex_bolt",
		OpKind::HexNut { .. } => "hex_nut",
		OpKind::Washer { .. } => "washer",
		OpKind::SocketHeadCapScrew { .. } => "socket_head_cap_screw",
		OpKind::Gt2Pulley { .. } => "gt2_pulley",
		OpKind::ChainSprocket { .. } => "chain_sprocket",
		OpKind::Shaft { .. } => "shaft",
		OpKind::ParallelKey { .. } => "parallel_key",
		OpKind::DowelPin { .. } => "dowel_pin",
		OpKind::CirclipExternal { .. } => "circlip_external",
		OpKind::CirclipInternal { .. } => "circlip_internal",
		OpKind::FlatHeadScrew { .. } => "flat_head_screw",
		OpKind::ButtonHeadScrew { .. } => "button_head_screw",
		OpKind::SetScrew { .. } => "set_screw",
		OpKind::LockNut { .. } => "lock_nut",
		OpKind::ThreadedRod { .. } => "threaded_rod",
		OpKind::Standoff { .. } => "standoff",
		OpKind::CompressionSpring { .. } => "compression_spring",
		OpKind::Extrusion2020 { .. } => "extrusion_2020",
		OpKind::Extrusion3030 { .. } => "extrusion_3030",
		OpKind::Tnut2020 { .. } => "tnut_2020",
		OpKind::ORing { .. } => "o_ring",
		OpKind::ORingCord { .. } => "o_ring_cord",
		OpKind::JawCouplingHub { .. } => "jaw_coupling_hub",
		OpKind::JawCouplingSpider { .. } => "jaw_coupling_spider",
		OpKind::SetScrewCoupling { .. } => "set_screw_coupling",
		OpKind::ClampCoupling { .. } => "clamp_coupling",
		OpKind::NemaMotor { .. } => "nema_motor",
		OpKind::NemaMountPlate { .. } => "nema_mount_plate",
		OpKind::LinearBearingLmuu { .. } => "linear_bearing_lmuu",
		OpKind::Sc8uuBlock { .. } => "sc8uu_block",
		OpKind::ShaftSupportSk8 { .. } => "shaft_support_sk8",
		OpKind::ShaftSupportShf8 { .. } => "shaft_support_shf8",
		OpKind::Mgn12Rail { .. } => "mgn12_rail",
		OpKind::Mgn12Carriage { .. } => "mgn12_carriage",
		OpKind::DeepGrooveBearing { .. } => "deep_groove_bearing",
		OpKind::FlangedBearing { .. } => "flanged_bearing",
		OpKind::ThrustBearing { .. } => "thrust_bearing",
		OpKind::Kp08PillowBlock { .. } => "kp08_pillow_block",
		OpKind::PipeBossG { .. } => "pipe_boss_g",
		OpKind::HoseBarb { .. } => "hose_barb",
		OpKind::ShoulderBolt { .. } => "shoulder_bolt",
		OpKind::SpringWasher { .. } => "spring_washer",
		OpKind::LeadScrewTr8 { .. } => "lead_screw_tr8",
		OpKind::LeadScrewNutTr8 { .. } => "lead_screw_nut_tr8",
		OpKind::GearRack { .. } => "gear_rack",
		OpKind::InternalGear { .. } => "internal_gear",
		OpKind::HeatsetInsertBoss { .. } => "heatset_insert_boss",
		OpKind::CirclipGrooveExternal { .. } => "circlip_groove_external",
		OpKind::CirclipGrooveInternal { .. } => "circlip_groove_internal",
		OpKind::ORingGroove { .. } => "o_ring_groove",
		OpKind::ORingFaceGland { .. } => "o_ring_face_gland",
		OpKind::ORingFaceGlandRacetrack { .. } => "o_ring_face_gland_racetrack",
		OpKind::NemaMountCut { .. } => "nema_mount_cut",
		OpKind::ServoPocket { .. } => "servo_pocket",
		OpKind::Tr8NutTrap { .. } => "tr8_nut_trap",
		OpKind::Pc4Port { .. } => "pc4_port",
		OpKind::TeardropHole { .. } => "teardrop_hole",
		OpKind::BoardMount { .. } => "board_mount",
		OpKind::BridgedCounterbore { .. } => "bridged_counterbore",
		OpKind::AsmInstance { .. } => "asm_instance",
		OpKind::AsmInstanceMesh { .. } => "asm_instance_mesh",
		OpKind::AsmMate { .. } => "asm_mate",
		OpKind::AsmMateAxis { .. } => "asm_mate_axis",
		OpKind::AsmMateFace { .. } => "asm_mate_face",
		OpKind::AsmSolve { .. } => "asm_solve",
		OpKind::AsmContacts { .. } => "asm_contacts",
		OpKind::AsmInterferenceVolume { .. } => "asm_interference_volume",
		OpKind::AsmMassProperties { .. } => "asm_mass_properties",
		OpKind::AsmExport { .. } => "asm_export",
		OpKind::AsmExportStep { .. } => "asm_export_step",
		OpKind::AsmSave { .. } => "asm_save",
		OpKind::GearTrainPoses { .. } => "gear_train_poses",
		OpKind::Gt2Belt { .. } => "gt2_belt",
		OpKind::Gt2CenterDistance { .. } => "gt2_center_distance",
		OpKind::Iso286Fit { .. } => "iso286_fit",
		OpKind::HeatsetSpec { .. } => "heatset_spec",
		OpKind::MetricCordGland { .. } => "metric_cord_gland",
		OpKind::RacetrackCordLength { .. } => "racetrack_cord_length",
		OpKind::PipeThreadG { .. } => "pipe_thread_g",
		OpKind::Drill { .. } => "drill",
		OpKind::ClearanceHole { .. } => "clearance_hole",
		OpKind::CounterboreHole { .. } => "counterbore_hole",
		OpKind::CountersinkHole { .. } => "countersink_hole",
		OpKind::TapDrillHole { .. } => "tap_drill_hole",
		OpKind::BoltCircle { .. } => "bolt_circle",
		OpKind::BearingSeat { .. } => "bearing_seat",
		OpKind::ThreadSpec { .. } => "thread_spec",
		OpKind::ThreadRidge { .. } => "thread_ridge",
		OpKind::ExportThreaded { .. } => "export_threaded",
	}
}

/// The authoritative catalogue every supported op tag, in declaration order returned by the
/// `describe` op and generated from the same source as [`op_tag`]. Length is pinned to the variant
/// count by `tests/describe.rs`; every entry is proven executable (never `unknown_op`) there too.
pub const OP_NAMES: &[&str] = &[
	"box",
	"cylinder",
	"sphere",
	"cone",
	"torus",
	"extrude",
	"extrude_with_holes",
	"extrude_tapered",
	"revolve",
	"loft",
	"sweep",
	"sketch",
	"sketch_extrude",
	"sketch_revolve",
	"union",
	"difference",
	"intersection",
	"union_all",
	"fillet_edge_near",
	"chamfer_edge_near",
	"fillet_circular_rim",
	"translate",
	"rotate_z",
	"rotate_x",
	"rotate_y",
	"pose",
	"mirror",
	"linear_pattern",
	"polar_pattern",
	"validate",
	"volume",
	"exact_volume",
	"mass_properties",
	"bounding_box",
	"wall_thickness",
	"draft_analysis",
	"assert",
	"assert_disjoint",
	"coincident_fit",
	"support_report",
	"clearance",
	"describe",
	"list_faces",
	"list_edges",
	"export_stl",
	"export_step",
	"export_3mf",
	"gyroid_block",
	"measure_dimension",
	"tpms",
	"hybrid_boolean",
	"implicit",
	"shell",
	"offset_solid",
	"shell_solid",
	"solid_from_implicit",
	"thin_wall",
	"min_ligament",
	"sample_density_grid",
	"mesh_density_grid",
	"load_part",
	"import_step",
	"import_mesh",
	"mesh_carve",
	"library_add",
	"library_search",
	"library_instantiate",
	"library_deprecate",
	"library_remove",
	"spur_gear",
	"hex_bolt",
	"hex_nut",
	"washer",
	"socket_head_cap_screw",
	"gt2_pulley",
	"chain_sprocket",
	"shaft",
	"parallel_key",
	"dowel_pin",
	"circlip_external",
	"circlip_internal",
	"flat_head_screw",
	"button_head_screw",
	"set_screw",
	"lock_nut",
	"threaded_rod",
	"standoff",
	"compression_spring",
	"extrusion_2020",
	"extrusion_3030",
	"tnut_2020",
	"o_ring",
	"o_ring_cord",
	"jaw_coupling_hub",
	"jaw_coupling_spider",
	"set_screw_coupling",
	"clamp_coupling",
	"nema_motor",
	"nema_mount_plate",
	"linear_bearing_lmuu",
	"sc8uu_block",
	"shaft_support_sk8",
	"shaft_support_shf8",
	"mgn12_rail",
	"mgn12_carriage",
	"deep_groove_bearing",
	"flanged_bearing",
	"thrust_bearing",
	"kp08_pillow_block",
	"pipe_boss_g",
	"hose_barb",
	"shoulder_bolt",
	"spring_washer",
	"lead_screw_tr8",
	"lead_screw_nut_tr8",
	"gear_rack",
	"internal_gear",
	"heatset_insert_boss",
	"circlip_groove_external",
	"circlip_groove_internal",
	"o_ring_groove",
	"o_ring_face_gland",
	"o_ring_face_gland_racetrack",
	"nema_mount_cut",
	"servo_pocket",
	"tr8_nut_trap",
	"pc4_port",
	"teardrop_hole",
	"board_mount",
	"bridged_counterbore",
	"asm_instance",
	"asm_instance_mesh",
	"asm_mate",
	"asm_mate_axis",
	"asm_mate_face",
	"asm_solve",
	"asm_contacts",
	"asm_interference_volume",
	"asm_mass_properties",
	"asm_export",
	"asm_export_step",
	"asm_save",
	"gear_train_poses",
	"gt2_belt",
	"gt2_center_distance",
	"iso286_fit",
	"heatset_spec",
	"metric_cord_gland",
	"racetrack_cord_length",
	"pipe_thread_g",
	"drill",
	"clearance_hole",
	"counterbore_hole",
	"countersink_hole",
	"tap_drill_hole",
	"bolt_circle",
	"bearing_seat",
	"thread_spec",
	"thread_ridge",
	"export_threaded",
];

/// Number of supported ops. Kept in lockstep with the `OpKind` variant count via [`op_tag`].
pub const OP_COUNT: usize = 160;

/// One parameter of an op, as served by `describe {name}`: the JSON wire name (post
/// `#[serde(rename)]` — e.g. `in`), a friendly type string (`number` / `int` / `string` /
/// `bool` / `id-ref` / `[x,y,z]` / `[[x,y]...]` / `object` / ...), whether the field is
/// required (no `Option` and no serde default), and the first sentence of its doc comment.
#[derive(Clone, Copy, Debug)]
pub struct ParamSpec {
	pub name: &'static str,
	pub ty: &'static str,
	pub required: bool,
	pub doc: &'static str,
}

/// Per-op parameter specs, parallel to [`OP_NAMES`] (same tags, same declaration order — pinned
/// by `tests/describe.rs`). Generated from the `OpKind` field lists by `tools/gen_discover.py`.
pub static OP_PARAMS: &[(&str, &[ParamSpec])] = &[
	("box", &[
		ParamSpec { name: "min", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "max", ty: "[x,y,z]", required: true, doc: "" },
	]),
	("cylinder", &[
		ParamSpec { name: "base", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "radius", ty: "number", required: true, doc: "" },
		ParamSpec { name: "height", ty: "number", required: true, doc: "" },
		ParamSpec { name: "segments", ty: "int", required: false, doc: "" },
	]),
	("sphere", &[
		ParamSpec { name: "center", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "radius", ty: "number", required: true, doc: "" },
		ParamSpec { name: "u", ty: "int", required: false, doc: "" },
		ParamSpec { name: "v", ty: "int", required: false, doc: "" },
	]),
	("cone", &[
		ParamSpec { name: "base", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "radius", ty: "number", required: true, doc: "" },
		ParamSpec { name: "height", ty: "number", required: true, doc: "" },
		ParamSpec { name: "segments", ty: "int", required: false, doc: "" },
	]),
	("torus", &[
		ParamSpec { name: "center", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "major", ty: "number", required: true, doc: "" },
		ParamSpec { name: "minor", ty: "number", required: true, doc: "" },
		ParamSpec { name: "ring_segments", ty: "int", required: false, doc: "" },
		ParamSpec { name: "tube_segments", ty: "int", required: false, doc: "" },
	]),
	("extrude", &[
		ParamSpec { name: "profile", ty: "[[x,y]...]", required: true, doc: "" },
		ParamSpec { name: "height", ty: "number", required: true, doc: "" },
	]),
	("extrude_with_holes", &[
		ParamSpec { name: "outer", ty: "[[x,y]...]", required: true, doc: "" },
		ParamSpec { name: "holes", ty: "[[[x,y]...]...]", required: true, doc: "" },
		ParamSpec { name: "height", ty: "number", required: true, doc: "" },
	]),
	("extrude_tapered", &[
		ParamSpec { name: "profile", ty: "[[x,y]...]", required: true, doc: "" },
		ParamSpec { name: "height", ty: "number", required: true, doc: "" },
		ParamSpec { name: "draft_deg", ty: "number", required: true, doc: "" },
	]),
	("revolve", &[
		ParamSpec { name: "profile", ty: "[[x,y]...]", required: true, doc: "" },
		ParamSpec { name: "segments", ty: "int", required: false, doc: "" },
	]),
	("loft", &[
		ParamSpec { name: "sections", ty: "[[[x,y,z]...]...]", required: true, doc: "" },
	]),
	("sweep", &[
		ParamSpec { name: "profile", ty: "[[x,y,z]...]", required: true, doc: "" },
		ParamSpec { name: "path", ty: "[[x,y,z]...]", required: true, doc: "" },
	]),
	("sketch", &[
		ParamSpec { name: "points", ty: "[[x,y]...]", required: true, doc: "" },
		ParamSpec { name: "segments", ty: "[[int,int]...]", required: false, doc: "" },
		ParamSpec { name: "arcs", ty: "[object...]", required: false, doc: "" },
		ParamSpec { name: "circles", ty: "[object...]", required: false, doc: "" },
		ParamSpec { name: "constraints", ty: "[object...]", required: false, doc: "" },
	]),
	("sketch_extrude", &[
		ParamSpec { name: "sketch", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "height", ty: "number", required: true, doc: "" },
	]),
	("sketch_revolve", &[
		ParamSpec { name: "sketch", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "segments", ty: "int", required: false, doc: "" },
	]),
	("union", &[
		ParamSpec { name: "a", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "b", ty: "id-ref", required: true, doc: "" },
	]),
	("difference", &[
		ParamSpec { name: "a", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "b", ty: "id-ref", required: true, doc: "" },
	]),
	("intersection", &[
		ParamSpec { name: "a", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "b", ty: "id-ref", required: true, doc: "" },
	]),
	("union_all", &[
		ParamSpec { name: "in", ty: "[id-ref...]", required: true, doc: "" },
	]),
	("fillet_edge_near", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "witness", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "radius", ty: "number", required: true, doc: "" },
		ParamSpec { name: "max_distance", ty: "number", required: false, doc: "Reject a witness farther than this from every edge (default: 10% of the solid's bounding-box diagonal)." },
	]),
	("chamfer_edge_near", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "witness", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "radius", ty: "number", required: true, doc: "" },
		ParamSpec { name: "max_distance", ty: "number", required: false, doc: "Same witness guard as `fillet_edge_near`'s `max_distance`." },
	]),
	("fillet_circular_rim", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "witness", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "radius", ty: "number", required: true, doc: "" },
		ParamSpec { name: "arc_segments", ty: "int", required: false, doc: "" },
	]),
	("translate", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "offset", ty: "[x,y,z]", required: true, doc: "" },
	]),
	("rotate_z", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "degrees", ty: "number", required: true, doc: "" },
	]),
	("rotate_x", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "degrees", ty: "number", required: true, doc: "" },
	]),
	("rotate_y", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "degrees", ty: "number", required: true, doc: "" },
	]),
	("pose", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "translate", ty: "[x,y,z]", required: false, doc: "" },
		ParamSpec { name: "rotate", ty: "object", required: false, doc: "" },
	]),
	("mirror", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "plane", ty: "object", required: true, doc: "" },
	]),
	("linear_pattern", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "count", ty: "int", required: true, doc: "Number of instances INCLUDING the original (2..=500)." },
		ParamSpec { name: "step", ty: "[x,y,z]", required: true, doc: "Per-instance offset vector (mm); must be non-zero." },
	]),
	("polar_pattern", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "count", ty: "int", required: true, doc: "Number of instances INCLUDING the original (2..=500)." },
		ParamSpec { name: "center", ty: "[x,y,z]", required: true, doc: "A point on the rotation axis." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Rotation axis — any non-zero vector, normalized internally." },
		ParamSpec { name: "step_deg", ty: "number", required: false, doc: "Angular pitch between instances in degrees (default `360 / count`, a full evenly-spaced ring)." },
	]),
	("validate", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
	]),
	("volume", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
	]),
	("exact_volume", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
	]),
	("mass_properties", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
	]),
	("bounding_box", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "envelope", ty: "[x,y,z]", required: false, doc: "" },
	]),
	("wall_thickness", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "flag_below", ty: "number", required: true, doc: "" },
	]),
	("draft_analysis", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "pull", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "min_deg", ty: "number", required: true, doc: "" },
	]),
	("assert", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "volume_within", ty: "object", required: false, doc: "Faceted (mesh) volume must land in this window." },
		ParamSpec { name: "exact_volume_within", ty: "object", required: false, doc: "Analytic `exact_volume` must land in this window." },
		ParamSpec { name: "genus", ty: "int", required: false, doc: "Topological genus must equal this." },
		ParamSpec { name: "shells", ty: "int", required: false, doc: "Shell count must equal this (e.g. 2 = two disjoint bodies after a union)." },
		ParamSpec { name: "closed", ty: "bool", required: false, doc: "`validate().closed` must equal this." },
		ParamSpec { name: "manifold", ty: "bool", required: false, doc: "`validate().manifold` must equal this." },
		ParamSpec { name: "valid", ty: "bool", required: false, doc: "`validate().is_valid()` (closed + manifold + sane genus) must equal this." },
	]),
	("assert_disjoint", &[
		ParamSpec { name: "a", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "b", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "min_clearance", ty: "number", required: false, doc: "Required clearance (mm); the assertion passes iff distance > this." },
		ParamSpec { name: "tol", ty: "number", required: false, doc: "Chord tolerance (mm) of the measurement tessellation — the distance is accurate to about this; for hard proofs keep `min_clearance` ≳ `tol`." },
	]),
	("coincident_fit", &[
		ParamSpec { name: "a", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "b", ty: "id-ref", required: true, doc: "" },
	]),
	("support_report", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "build_dir", ty: "[x,y,z]", required: false, doc: "" },
		ParamSpec { name: "overhang_deg", ty: "number", required: false, doc: "" },
	]),
	("clearance", &[
		ParamSpec { name: "a", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "b", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "tol", ty: "number", required: false, doc: "" },
	]),
	("describe", &[
		ParamSpec { name: "name", ty: "string", required: false, doc: "" },
	]),
	("list_faces", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
	]),
	("list_edges", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
	]),
	("export_stl", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "file", ty: "string", required: true, doc: "" },
		ParamSpec { name: "tol", ty: "number", required: false, doc: "" },
		ParamSpec { name: "voxel", ty: "number", required: false, doc: "Voxel size for the heal fallback (default 0.3 mm)." },
	]),
	("export_step", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "file", ty: "string", required: true, doc: "" },
	]),
	("export_3mf", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "file", ty: "string", required: true, doc: "" },
		ParamSpec { name: "tol", ty: "number", required: false, doc: "" },
		ParamSpec { name: "voxel", ty: "number", required: false, doc: "Voxel size for the heal fallback (default 0.3 mm)." },
	]),
	("gyroid_block", &[
		ParamSpec { name: "center", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "half", ty: "number", required: true, doc: "" },
		ParamSpec { name: "scale", ty: "number", required: true, doc: "Gyroid frequency scale (cells shrink as `scale` grows; try 0.35)." },
		ParamSpec { name: "thickness", ty: "number", required: true, doc: "Shell thickness (mm)." },
		ParamSpec { name: "voxel", ty: "number", required: true, doc: "Voxel size (mm) for the dual-contour grid." },
		ParamSpec { name: "file", ty: "string", required: true, doc: "" },
	]),
	("measure_dimension", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "kind", ty: "string", required: true, doc: "`\"point_point\"` / `\"face_face\"` / `\"diameter\"`." },
		ParamSpec { name: "a", ty: "[x,y,z]", required: false, doc: "`point_point`: first point." },
		ParamSpec { name: "b", ty: "[x,y,z]", required: false, doc: "`point_point`: second point." },
		ParamSpec { name: "near", ty: "[x,y,z]", required: false, doc: "`diameter`: witness selecting the measured cylinder/sphere face." },
	]),
	("tpms", &[
		ParamSpec { name: "kind", ty: "string", required: true, doc: "Family: `gyroid` / `schwarz_p` / `diamond` / `neovius` / `schoen_iwp` / `fischer_koch_s`." },
		ParamSpec { name: "min", ty: "[x,y,z]", required: true, doc: "Lattice block corner (mm)." },
		ParamSpec { name: "max", ty: "[x,y,z]", required: true, doc: "Opposite corner (mm)." },
		ParamSpec { name: "cell", ty: "number", required: true, doc: "Unit-cell edge length (mm)." },
		ParamSpec { name: "mode", ty: "string", required: false, doc: "`\"network\"` (default) or `\"sheet\"`." },
		ParamSpec { name: "level", ty: "number", required: false, doc: "network: iso-level (default 0 ≈ 50% solid; negative thins)." },
		ParamSpec { name: "voxel", ty: "number", required: false, doc: "Voxel size (mm) for the extraction grid (default 0.3)." },
		ParamSpec { name: "file", ty: "string", required: true, doc: "Output mesh path — the extension picks the format (`.stl` / `.3mf`)." },
	]),
	("hybrid_boolean", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "The exact B-rep operand (a bound solid)." },
		ParamSpec { name: "field", ty: "object", required: false, doc: "Implicit operand: a nestable CSG tree with finite bounds (exclusive with `file`; clamp an unbounded field by intersecting with a box)." },
		ParamSpec { name: "file", ty: "string", required: false, doc: "Mesh-file operand (`.stl`/`.obj`/`.3mf`/`.ply`; exclusive with `field`)." },
		ParamSpec { name: "bool", ty: "string", required: true, doc: "Which boolean: `\"union\"` / `\"difference\"` / `\"intersection\"`." },
		ParamSpec { name: "voxel", ty: "number", required: false, doc: "Voxel size (mm): the field operand's meshing lattice, and the healed fallback's resampling lattice (default 0.3)." },
		ParamSpec { name: "out", ty: "string", required: true, doc: "Output mesh path — the extension picks the format (`.stl` / `.3mf`)." },
	]),
	("implicit", &[
		ParamSpec { name: "expr", ty: "object", required: true, doc: "The recursive expression tree (parsed with JSON-path errors)." },
		ParamSpec { name: "voxel", ty: "number", required: true, doc: "Voxel size (mm) for the extraction grid." },
		ParamSpec { name: "mesher", ty: "string", required: false, doc: "" },
		ParamSpec { name: "domain", ty: "object", required: false, doc: "Explicit meshing box; default: the tree's bounds padded by 3·voxel." },
		ParamSpec { name: "file", ty: "string", required: false, doc: "Optional output file — the extension picks the format (`.stl`/`.3mf`)." },
	]),
	("shell", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "wall", ty: "number", required: true, doc: "Wall thickness (mm), > 0 and at least 2·`voxel` so the grid resolves it." },
		ParamSpec { name: "voxel", ty: "number", required: false, doc: "Voxel size (mm) for the SDF re-mesh (default 0.3)." },
		ParamSpec { name: "file", ty: "string", required: false, doc: "Optional output file — the extension picks the format (`.stl`/`.3mf`)." },
	]),
	("offset_solid", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "delta", ty: "number", required: true, doc: "Signed offset (mm): positive grows, negative shrinks." },
		ParamSpec { name: "voxel", ty: "number", required: false, doc: "Voxel size (mm) of the re-extraction lattice (default 0.3)." },
	]),
	("shell_solid", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "thickness", ty: "number", required: true, doc: "Wall thickness (mm), > 0 and at least 2·`voxel` so the grid resolves it." },
		ParamSpec { name: "voxel", ty: "number", required: false, doc: "Voxel size (mm) of the re-extraction lattice (default 0.3)." },
	]),
	("solid_from_implicit", &[
		ParamSpec { name: "expr", ty: "object", required: true, doc: "The implicit expression tree (same grammar as the `implicit` op)." },
		ParamSpec { name: "voxel", ty: "number", required: true, doc: "Extraction voxel size (mm) — also the chord fidelity of every face." },
		ParamSpec { name: "domain", ty: "object", required: false, doc: "Explicit meshing box; default: the tree's own (finite) bounds." },
	]),
	("thin_wall", &[
		ParamSpec { name: "in", ty: "id-ref", required: false, doc: "A bound solid id (exclusive with `expr`)." },
		ParamSpec { name: "expr", ty: "object", required: false, doc: "An implicit expression tree (exclusive with `in`)." },
		ParamSpec { name: "t_min", ty: "number", required: true, doc: "Walls thinner than this (mm) are counted in `below_count`." },
		ParamSpec { name: "samples", ty: "int", required: false, doc: "Sampling lattice points per axis, 8..=256 (default 64; cost ~samples³)." },
		ParamSpec { name: "domain", ty: "object", required: false, doc: "Explicit census box; default: the solid's bounding box / the tree's bounds." },
	]),
	("min_ligament", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "Planned hole center on the entry face." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Drilling direction, INTO the material (hole-wizard convention)." },
		ParamSpec { name: "d", ty: "number", required: true, doc: "Planned bore **diameter** (mm)." },
	]),
	("sample_density_grid", &[
		ParamSpec { name: "in", ty: "id-ref", required: false, doc: "A bound solid id (exclusive with `expr`)." },
		ParamSpec { name: "expr", ty: "object", required: false, doc: "An implicit expression tree (exclusive with `in`)." },
		ParamSpec { name: "origin", ty: "[x,y,z]", required: true, doc: "Grid origin (mm) — the LOW corner of voxel (0,0,0), not its center." },
		ParamSpec { name: "voxel", ty: "number", required: true, doc: "Isotropic voxel size h (mm)." },
		ParamSpec { name: "shape", ty: "[int,int,int]", required: true, doc: "Grid shape (nx, ny, nz)." },
		ParamSpec { name: "supersample", ty: "int", required: false, doc: "Sub-points per axis per voxel for fractional densities (default 2)." },
		ParamSpec { name: "file", ty: "string", required: true, doc: "Output `.npy` path (relative joins `--out-dir`)." },
	]),
	("mesh_density_grid", &[
		ParamSpec { name: "npy", ty: "string", required: true, doc: "Input `.npy` (float32/float64, C-order, shape `(nx,ny,nz)`)." },
		ParamSpec { name: "origin", ty: "[x,y,z]", required: true, doc: "Grid origin (mm) — low corner of voxel (0,0,0)." },
		ParamSpec { name: "voxel", ty: "number", required: true, doc: "Isotropic voxel size h (mm)." },
		ParamSpec { name: "iso", ty: "number", required: false, doc: "Density threshold: material where `rho >= iso` (default 0.5)." },
		ParamSpec { name: "file", ty: "string", required: true, doc: "Output mesh path (`.stl`/`.3mf`)." },
	]),
	("load_part", &[
		ParamSpec { name: "file", ty: "string", required: true, doc: "" },
	]),
	("import_step", &[
		ParamSpec { name: "file", ty: "string", required: true, doc: "" },
	]),
	("import_mesh", &[
		ParamSpec { name: "file", ty: "string", required: true, doc: "" },
		ParamSpec { name: "heal", ty: "bool", required: false, doc: "Repair before the receipt: cap boundary loops (`fill_holes`) and split non-manifold junctions (`make_manifold`)." },
		ParamSpec { name: "out", ty: "string", required: false, doc: "Optional re-write of the welded/healed mesh — the extension picks the format (`.stl` / `.3mf`)." },
	]),
	("mesh_carve", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "file", ty: "string", required: true, doc: "The mesh operand file (`.stl` / `.obj` / `.3mf` / `.ply`)." },
		ParamSpec { name: "bool", ty: "string", required: true, doc: "Which boolean: `\"union\"` / `\"difference\"` / `\"intersection\"`." },
		ParamSpec { name: "voxel", ty: "number", required: false, doc: "Voxel size (mm) of the resampling lattice (default 0.3)." },
		ParamSpec { name: "out", ty: "string", required: true, doc: "Output mesh path — the extension picks the format (`.stl` / `.3mf`)." },
	]),
	("library_add", &[
		ParamSpec { name: "dir", ty: "string", required: true, doc: "Library directory (relative joins `--out-dir`; created on demand)." },
		ParamSpec { name: "part", ty: "object", required: false, doc: "The candidate part envelope INLINE (exclusive with `part_file`)." },
		ParamSpec { name: "part_file", ty: "string", required: false, doc: "Path to the candidate `.lmcpart` (exclusive with `part`)." },
		ParamSpec { name: "meta", ty: "object", required: true, doc: "Identity, provenance (caller-supplied date) and parameter interface." },
	]),
	("library_search", &[
		ParamSpec { name: "dir", ty: "string", required: true, doc: "Library directory." },
		ParamSpec { name: "text", ty: "string", required: false, doc: "Case-insensitive substring over name/category/description/tags (empty matches all)." },
		ParamSpec { name: "tags", ty: "[string...]", required: false, doc: "Tags the entry must all carry (case-insensitive)." },
	]),
	("library_instantiate", &[
		ParamSpec { name: "dir", ty: "string", required: true, doc: "Library directory." },
		ParamSpec { name: "name", ty: "string", required: true, doc: "Entry name." },
		ParamSpec { name: "version", ty: "int", required: false, doc: "Entry version (default: the highest admitted version)." },
		ParamSpec { name: "params", ty: "object", required: false, doc: "Parameter values; unset parameters take their declared defaults." },
	]),
	("library_deprecate", &[
		ParamSpec { name: "dir", ty: "string", required: true, doc: "Library directory." },
		ParamSpec { name: "name", ty: "string", required: true, doc: "Entry name." },
	]),
	("library_remove", &[
		ParamSpec { name: "dir", ty: "string", required: true, doc: "Library directory." },
		ParamSpec { name: "name", ty: "string", required: true, doc: "Entry name." },
		ParamSpec { name: "force", ty: "bool", required: false, doc: "Skip the dependents refusal (default false)." },
	]),
	("spur_gear", &[
		ParamSpec { name: "module", ty: "number", required: true, doc: "" },
		ParamSpec { name: "teeth", ty: "int", required: true, doc: "" },
		ParamSpec { name: "face_width", ty: "number", required: true, doc: "" },
		ParamSpec { name: "bore", ty: "number", required: true, doc: "Bore **diameter** (mm)." },
		ParamSpec { name: "pressure_angle_deg", ty: "number", required: false, doc: "" },
		ParamSpec { name: "keyway", ty: "bool", required: false, doc: "Cut the DIN 6885-1 hub keyway sized for `bore` (default false)." },
	]),
	("hex_bolt", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
	]),
	("hex_nut", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
	]),
	("washer", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
	]),
	("socket_head_cap_screw", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
	]),
	("gt2_pulley", &[
		ParamSpec { name: "teeth", ty: "int", required: true, doc: "" },
		ParamSpec { name: "belt_width", ty: "number", required: true, doc: "" },
		ParamSpec { name: "bore", ty: "number", required: true, doc: "Bore **diameter** (mm); `bore_d` (the Document field name) is an alias." },
		ParamSpec { name: "flanged", ty: "bool", required: false, doc: "Add a retaining flange on each end (default false)." },
	]),
	("chain_sprocket", &[
		ParamSpec { name: "pitch", ty: "number", required: true, doc: "" },
		ParamSpec { name: "roller_d", ty: "number", required: true, doc: "" },
		ParamSpec { name: "teeth", ty: "int", required: true, doc: "" },
		ParamSpec { name: "bore", ty: "number", required: true, doc: "Bore **diameter** (mm); `bore_d` (the Document field name) is an alias." },
	]),
	("shaft", &[
		ParamSpec { name: "d", ty: "number", required: true, doc: "Shaft **diameter** (mm)." },
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
		ParamSpec { name: "keyway", ty: "object", required: false, doc: "Optional keyway slot; its width/depth auto-size from the DIN 6885-1 table for `d`." },
	]),
	("parallel_key", &[
		ParamSpec { name: "b", ty: "number", required: true, doc: "" },
		ParamSpec { name: "h", ty: "number", required: true, doc: "" },
		ParamSpec { name: "l", ty: "number", required: true, doc: "" },
	]),
	("dowel_pin", &[
		ParamSpec { name: "d", ty: "number", required: true, doc: "Pin **diameter** (mm), an ISO 2338 table size." },
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
	]),
	("circlip_external", &[
		ParamSpec { name: "shaft_d", ty: "number", required: true, doc: "" },
	]),
	("circlip_internal", &[
		ParamSpec { name: "bore_d", ty: "number", required: true, doc: "" },
	]),
	("flat_head_screw", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
	]),
	("button_head_screw", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
	]),
	("set_screw", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
	]),
	("lock_nut", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
	]),
	("threaded_rod", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
	]),
	("standoff", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
	]),
	("compression_spring", &[
		ParamSpec { name: "wire_d", ty: "number", required: true, doc: "Wire **diameter** (mm)." },
		ParamSpec { name: "outer_d", ty: "number", required: true, doc: "Coil outside **diameter** (mm)." },
		ParamSpec { name: "pitch", ty: "number", required: true, doc: "Axial advance per turn (mm), must exceed `wire_d`." },
		ParamSpec { name: "turns", ty: "number", required: true, doc: "Active turns (may be fractional)." },
	]),
	("extrusion_2020", &[
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
	]),
	("extrusion_3030", &[
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
	]),
	("tnut_2020", &[]),
	("o_ring", &[
		ParamSpec { name: "dash", ty: "int", required: true, doc: "AS568 dash number (e.g. `214`)." },
	]),
	("o_ring_cord", &[
		ParamSpec { name: "ring_id", ty: "number", required: true, doc: "Ring inside **diameter** (mm) — free, unlike the AS568 dash table." },
		ParamSpec { name: "cord_d", ty: "number", required: true, doc: "Cord cross-section **diameter** (mm), a stocked metric size." },
	]),
	("jaw_coupling_hub", &[
		ParamSpec { name: "od", ty: "number", required: true, doc: "Body outer **diameter** (a table size: 20, 25, 30, 40)." },
		ParamSpec { name: "bore", ty: "number", required: true, doc: "Bore **diameter** (mm), within the size row's range." },
	]),
	("jaw_coupling_spider", &[
		ParamSpec { name: "od", ty: "number", required: true, doc: "Body outer **diameter** (a table size: 20, 25, 30, 40)." },
	]),
	("set_screw_coupling", &[
		ParamSpec { name: "bore1", ty: "number", required: true, doc: "Bore at z = 0 (a stocked size)." },
		ParamSpec { name: "bore2", ty: "number", required: true, doc: "Bore at z = L (a stocked size)." },
	]),
	("clamp_coupling", &[
		ParamSpec { name: "bore1", ty: "number", required: true, doc: "Bore at z = 0 (a stocked size)." },
		ParamSpec { name: "bore2", ty: "number", required: true, doc: "Bore at z = L (a stocked size)." },
	]),
	("nema_motor", &[
		ParamSpec { name: "frame", ty: "int", required: true, doc: "NEMA frame number (17 or 23)." },
		ParamSpec { name: "body_len", ty: "number", required: true, doc: "Body length below the faceplate, mm." },
	]),
	("nema_mount_plate", &[
		ParamSpec { name: "frame", ty: "int", required: true, doc: "NEMA frame number (17 or 23)." },
		ParamSpec { name: "thickness", ty: "number", required: true, doc: "Plate thickness, mm." },
		ParamSpec { name: "margin", ty: "number", required: true, doc: "Extra plate width beyond the motor face, per side (≥ 0)." },
	]),
	("linear_bearing_lmuu", &[
		ParamSpec { name: "bore", ty: "number", required: true, doc: "Shaft bore **diameter**: 8 (LM8UU) or 12 (LM12UU)." },
	]),
	("sc8uu_block", &[]),
	("shaft_support_sk8", &[]),
	("shaft_support_shf8", &[]),
	("mgn12_rail", &[
		ParamSpec { name: "length", ty: "number", required: true, doc: "Rail length, mm (≥ one 25 mm pitch)." },
	]),
	("mgn12_carriage", &[]),
	("deep_groove_bearing", &[
		ParamSpec { name: "designation", ty: "string", required: true, doc: "Seat-table designation: \"603\", \"608\", \"625\", \"688\", \"6000\", \"6001\", \"6804\"." },
	]),
	("flanged_bearing", &[
		ParamSpec { name: "designation", ty: "string", required: true, doc: "\"F608\" (8 × 22 × 7, flange Ø25 × 1.5) or \"F623\" (3 × 10 × 4, Ø11.5 × 0.6)." },
	]),
	("thrust_bearing", &[
		ParamSpec { name: "designation", ty: "string", required: true, doc: "\"51100\" (10 × 24 × 9) or \"51101\" (12 × 26 × 9)." },
	]),
	("kp08_pillow_block", &[]),
	("pipe_boss_g", &[
		ParamSpec { name: "designation", ty: "string", required: true, doc: "\"G1/8\", \"G1/4\", \"G3/8\" or \"G1/2\"." },
		ParamSpec { name: "wall", ty: "number", required: true, doc: "Radial wall beyond the thread major Ø, mm (≥ 1)." },
		ParamSpec { name: "length", ty: "number", required: true, doc: "Boss length along +Z, mm (must contain chamfer + one pitch)." },
	]),
	("hose_barb", &[
		ParamSpec { name: "hose_id", ty: "number", required: true, doc: "Hose inner **diameter**, mm." },
		ParamSpec { name: "barbs", ty: "int", required: true, doc: "Number of sawtooth teeth (≥ 1)." },
	]),
	("shoulder_bolt", &[
		ParamSpec { name: "shoulder_d", ty: "number", required: true, doc: "Shoulder **diameter**: 6.5, 8, 10, 13 or 16 (the ISO 7379 sizes)." },
		ParamSpec { name: "shoulder_len", ty: "number", required: true, doc: "Ground-shoulder length, mm (the ordering length)." },
	]),
	("spring_washer", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "Nominal thread size: 3, 4, 5, 6, 8, 10 or 12." },
	]),
	("lead_screw_tr8", &[
		ParamSpec { name: "length", ty: "number", required: true, doc: "Screw length, mm." },
		ParamSpec { name: "lead", ty: "number", required: true, doc: "Lead: 2 (1-start), 4 (2-start) or 8 (4-start), all pitch 2." },
	]),
	("lead_screw_nut_tr8", &[]),
	("gear_rack", &[
		ParamSpec { name: "module", ty: "number", required: true, doc: "" },
		ParamSpec { name: "length", ty: "number", required: true, doc: "" },
		ParamSpec { name: "width", ty: "number", required: true, doc: "" },
		ParamSpec { name: "pressure_angle_deg", ty: "number", required: false, doc: "" },
	]),
	("internal_gear", &[
		ParamSpec { name: "module", ty: "number", required: true, doc: "" },
		ParamSpec { name: "teeth", ty: "int", required: true, doc: "" },
		ParamSpec { name: "face_width", ty: "number", required: true, doc: "" },
		ParamSpec { name: "rim_od", ty: "number", required: true, doc: "Rim outer **diameter** (mm), must exceed the root circle `m(z + 2.5)`." },
		ParamSpec { name: "pressure_angle_deg", ty: "number", required: false, doc: "" },
	]),
	("heatset_insert_boss", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "Boss centre on the host face." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Outward face normal." },
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
	]),
	("circlip_groove_external", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "shaft_d", ty: "number", required: true, doc: "" },
	]),
	("circlip_groove_internal", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "bore_d", ty: "number", required: true, doc: "" },
	]),
	("o_ring_groove", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "dash", ty: "int", required: true, doc: "" },
	]),
	("o_ring_face_gland", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "Gland centre **on the face**." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Outward face normal; the groove sinks along `-axis`." },
		ParamSpec { name: "gland_center_d", ty: "number", required: true, doc: "Channel centreline **diameter** (mm)." },
		ParamSpec { name: "cord_d", ty: "number", required: true, doc: "Cord cross-section **diameter** (mm), a stocked metric size." },
	]),
	("o_ring_face_gland_racetrack", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "Racetrack centre **on the face**." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Outward face normal; the groove sinks along `-axis`." },
		ParamSpec { name: "x_len", ty: "number", required: true, doc: "Centreline rectangle overall length along the face-frame x axis (mm)." },
		ParamSpec { name: "y_len", ty: "number", required: true, doc: "Centreline rectangle overall length along the face-frame y axis (mm)." },
		ParamSpec { name: "corner_r", ty: "number", required: true, doc: "Centreline corner radius (mm), at least half the groove width." },
		ParamSpec { name: "cord_d", ty: "number", required: true, doc: "Cord cross-section **diameter** (mm), a stocked metric size." },
	]),
	("nema_mount_cut", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "Motor axis position on the face." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Outward face normal." },
		ParamSpec { name: "frame", ty: "int", required: true, doc: "NEMA frame number (17 or 23)." },
		ParamSpec { name: "through", ty: "number", required: true, doc: "Material span the holes cut through, mm." },
	]),
	("servo_pocket", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "Pocket centre on the face." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Outward face normal." },
		ParamSpec { name: "model", ty: "string", required: true, doc: "Servo model name (\"sg90\" or \"mg996r\")." },
		ParamSpec { name: "through", ty: "number", required: true, doc: "Material span the pocket cuts through, mm." },
	]),
	("tr8_nut_trap", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "Screw axis position on the face." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Outward face normal." },
		ParamSpec { name: "through", ty: "number", required: true, doc: "Material span the bore/holes cut through, mm (> 3.7 recess depth)." },
	]),
	("pc4_port", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "Port centre on the face." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Outward face normal." },
		ParamSpec { name: "m", ty: "number", required: true, doc: "Fitting thread: 6 (PC4-M6, Ø5 × 6 pocket) or 10 (PC4-M10, Ø9 × 7)." },
		ParamSpec { name: "through", ty: "number", required: true, doc: "Total material depth, mm (> pocket depth)." },
	]),
	("teardrop_hole", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "Hole centre on the entry face." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Drilling direction, INTO the material (hole-wizard convention)." },
		ParamSpec { name: "up", ty: "[x,y,z]", required: true, doc: "Build (print-bed +Z) direction; must not be parallel to `axis`." },
		ParamSpec { name: "d", ty: "number", required: true, doc: "Bore **diameter**, mm." },
		ParamSpec { name: "through", ty: "number", required: true, doc: "Material span, mm." },
	]),
	("board_mount", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "Pattern datum on the face: board bottom-left corner (rpi/arduino_uno) or pattern centre (vesa75/vesa100)." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Drilling direction, INTO the material." },
		ParamSpec { name: "board", ty: "string", required: true, doc: "\"rpi\", \"arduino_uno\", \"vesa75\" or \"vesa100\"." },
	]),
	("bridged_counterbore", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "Hole centre on the entry face." },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "Drilling direction, INTO the material (hole-wizard convention)." },
		ParamSpec { name: "m", ty: "number", required: true, doc: "Nominal screw size M2–M12 (DIN 974 pocket, ISO 273 medium bore)." },
		ParamSpec { name: "through", ty: "number", required: true, doc: "Total material depth, mm (> pocket + bridge)." },
		ParamSpec { name: "bridge", ty: "number", required: true, doc: "Sacrificial membrane thickness, mm (one layer height, e.g. 0.2–0.3)." },
	]),
	("asm_instance", &[
		ParamSpec { name: "solid", ty: "string", required: true, doc: "Id of the bound solid to place (built by any earlier solid op)." },
		ParamSpec { name: "name", ty: "string", required: false, doc: "Display name in receipts/BOM (default: this op's id)." },
		ParamSpec { name: "translate", ty: "[x,y,z]", required: false, doc: "Seed translation (mm)." },
		ParamSpec { name: "rotate", ty: "object", required: false, doc: "Seed rotation (applied before the translation)." },
		ParamSpec { name: "material", ty: "object", required: false, doc: "Material for mass/BOM receipts: `{name, density_g_cm3}`." },
	]),
	("asm_instance_mesh", &[
		ParamSpec { name: "file", ty: "string", required: true, doc: "Mesh file path (relative paths resolve against the input base)." },
		ParamSpec { name: "name", ty: "string", required: false, doc: "Display name in receipts/BOM (default: this op's id)." },
		ParamSpec { name: "translate", ty: "[x,y,z]", required: false, doc: "Seed translation (mm)." },
		ParamSpec { name: "rotate", ty: "object", required: false, doc: "Seed rotation (applied before the translation)." },
		ParamSpec { name: "material", ty: "object", required: false, doc: "Material for mass/BOM receipts: `{name, density_g_cm3}`." },
	]),
	("asm_mate", &[
		ParamSpec { name: "kind", ty: "string", required: true, doc: "Mate kind (see list above)." },
		ParamSpec { name: "a", ty: "id-ref", required: true, doc: "First instance (an `asm_instance`/`asm_instance_mesh` op id)." },
		ParamSpec { name: "b", ty: "id-ref", required: false, doc: "Second instance (required for every kind except `fixed`)." },
		ParamSpec { name: "a_point", ty: "[x,y,z]", required: false, doc: "Point on `a` (local mm) — coincident/distance." },
		ParamSpec { name: "b_point", ty: "[x,y,z]", required: false, doc: "Point on `b` (local mm) — coincident/distance." },
		ParamSpec { name: "a_dir", ty: "[x,y,z]", required: false, doc: "Direction on `a` (local) — parallel/angle." },
		ParamSpec { name: "b_dir", ty: "[x,y,z]", required: false, doc: "Direction on `b` (local) — parallel/angle." },
		ParamSpec { name: "a_axis_point", ty: "[x,y,z]", required: false, doc: "Axis point on `a` (local mm) — concentric/axis_distance." },
		ParamSpec { name: "a_axis_dir", ty: "[x,y,z]", required: false, doc: "Axis direction on `a` (local) — concentric/axis_distance." },
		ParamSpec { name: "b_axis_point", ty: "[x,y,z]", required: false, doc: "Axis point on `b` (local mm) — concentric/axis_distance." },
		ParamSpec { name: "b_axis_dir", ty: "[x,y,z]", required: false, doc: "Axis direction on `b` (local) — concentric/axis_distance." },
		ParamSpec { name: "distance", ty: "number", required: false, doc: "Target separation (mm) — distance/axis_distance." },
		ParamSpec { name: "degrees", ty: "number", required: false, doc: "Target angle in degrees (0–180) — angle." },
	]),
	("asm_mate_axis", &[
		ParamSpec { name: "a", ty: "id-ref", required: true, doc: "First instance (op id)." },
		ParamSpec { name: "a_witness", ty: "[x,y,z]", required: true, doc: "Point near the axis-carrying face on `a`'s solid (LOCAL mm)." },
		ParamSpec { name: "b", ty: "id-ref", required: true, doc: "Second instance (op id)." },
		ParamSpec { name: "b_witness", ty: "[x,y,z]", required: true, doc: "Point near the axis-carrying face on `b`'s solid (LOCAL mm)." },
		ParamSpec { name: "distance", ty: "number", required: false, doc: "Optional center distance (mm): axis_distance instead of concentric." },
	]),
	("asm_mate_face", &[
		ParamSpec { name: "a", ty: "id-ref", required: true, doc: "First instance (op id)." },
		ParamSpec { name: "a_witness", ty: "[x,y,z]", required: true, doc: "Point near the mating face on `a`'s solid (LOCAL mm)." },
		ParamSpec { name: "b", ty: "id-ref", required: true, doc: "Second instance (op id)." },
		ParamSpec { name: "b_witness", ty: "[x,y,z]", required: true, doc: "Point near the mating face on `b`'s solid (LOCAL mm)." },
		ParamSpec { name: "offset", ty: "number", required: false, doc: "Face separation along the normal (mm, default 0 = flush)." },
	]),
	("asm_solve", &[
		ParamSpec { name: "iterations", ty: "int", required: false, doc: "Relaxation sweep budget (default 256)." },
		ParamSpec { name: "max_residual", ty: "number", required: false, doc: "Residual gate (default 1e-6)." },
		ParamSpec { name: "allow_unconverged", ty: "bool", required: false, doc: "Report an unconverged solve as ok:true with `converged:false` instead of failing (default false — loud)." },
	]),
	("asm_contacts", &[
		ParamSpec { name: "window", ty: "number", required: false, doc: "Proximity window (mm, default 1.0)." },
		ParamSpec { name: "tol", ty: "number", required: false, doc: "Chord tolerance for exact tessellation (mm, default 0.05)." },
	]),
	("asm_interference_volume", &[
		ParamSpec { name: "a", ty: "id-ref", required: true, doc: "First instance (op id)." },
		ParamSpec { name: "b", ty: "id-ref", required: true, doc: "Second instance (op id)." },
		ParamSpec { name: "voxel", ty: "number", required: false, doc: "Sampling cell size (mm, default 0.3)." },
	]),
	("asm_mass_properties", &[]),
	("asm_export", &[
		ParamSpec { name: "file", ty: "string", required: true, doc: "Merged output path (`.stl` / `.3mf`)." },
		ParamSpec { name: "parts_dir", ty: "string", required: false, doc: "Optional directory for per-instance STLs." },
		ParamSpec { name: "tol", ty: "number", required: false, doc: "Chord tolerance for exact tessellation (mm, default 0.05)." },
		ParamSpec { name: "voxel", ty: "number", required: false, doc: "Voxel size for the watertight heal fallback (mm, default 0.3)." },
	]),
	("asm_export_step", &[
		ParamSpec { name: "file", ty: "string", required: true, doc: "Output path (`.step`)." },
	]),
	("asm_save", &[
		ParamSpec { name: "file", ty: "string", required: true, doc: "Output `.lmcasm` path." },
		ParamSpec { name: "name", ty: "string", required: false, doc: "Assembly name in the envelope (default: the file stem)." },
		ParamSpec { name: "parts_dir", ty: "string", required: false, doc: "Directory (relative to the `.lmcasm`) for exported instance meshes." },
	]),
	("gear_train_poses", &[
		ParamSpec { name: "sun_teeth", ty: "int", required: true, doc: "Sun tooth count (input)." },
		ParamSpec { name: "ring1_teeth", ty: "int", required: true, doc: "Grounded ring tooth count." },
		ParamSpec { name: "planet_a_teeth", ty: "int", required: true, doc: "First planet band tooth count." },
		ParamSpec { name: "planet_b_teeth", ty: "int", required: true, doc: "Second (stepped) planet band tooth count." },
		ParamSpec { name: "ring2_teeth", ty: "int", required: true, doc: "Output ring tooth count." },
		ParamSpec { name: "n_planets", ty: "int", required: true, doc: "Number of equally spaced planets." },
		ParamSpec { name: "module", ty: "number", required: true, doc: "Gear module (mm) — scales tooth counts into radii." },
		ParamSpec { name: "theta_deg", ty: "number", required: true, doc: "Input (sun) angle in degrees." },
	]),
	("gt2_belt", &[
		ParamSpec { name: "center_distance", ty: "number", required: true, doc: "" },
		ParamSpec { name: "t1", ty: "int", required: true, doc: "" },
		ParamSpec { name: "t2", ty: "int", required: true, doc: "" },
	]),
	("gt2_center_distance", &[
		ParamSpec { name: "belt_teeth", ty: "int", required: true, doc: "" },
		ParamSpec { name: "t1", ty: "int", required: true, doc: "" },
		ParamSpec { name: "t2", ty: "int", required: true, doc: "" },
	]),
	("iso286_fit", &[
		ParamSpec { name: "d", ty: "number", required: true, doc: "" },
		ParamSpec { name: "fit", ty: "string", required: true, doc: "" },
	]),
	("heatset_spec", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
	]),
	("metric_cord_gland", &[
		ParamSpec { name: "cord_d", ty: "number", required: true, doc: "" },
	]),
	("racetrack_cord_length", &[
		ParamSpec { name: "x_len", ty: "number", required: true, doc: "" },
		ParamSpec { name: "y_len", ty: "number", required: true, doc: "" },
		ParamSpec { name: "corner_r", ty: "number", required: true, doc: "" },
	]),
	("pipe_thread_g", &[
		ParamSpec { name: "designation", ty: "string", required: true, doc: "\"G1/8\", \"G1/4\", \"G3/8\" or \"G1/2\"." },
	]),
	("drill", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "d", ty: "number", required: true, doc: "Hole **diameter** (mm)." },
		ParamSpec { name: "depth", ty: "number", required: false, doc: "Full-diameter depth of a blind hole (exclusive with `through`)." },
		ParamSpec { name: "through", ty: "number", required: false, doc: "Material span of a through hole (exclusive with `depth`)." },
		ParamSpec { name: "segments", ty: "int", required: false, doc: "Tool facet count (default 32)." },
	]),
	("clearance_hole", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
		ParamSpec { name: "fit", ty: "string", required: false, doc: "" },
		ParamSpec { name: "segments", ty: "int", required: false, doc: "" },
	]),
	("counterbore_hole", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
		ParamSpec { name: "fit", ty: "string", required: false, doc: "" },
		ParamSpec { name: "segments", ty: "int", required: false, doc: "" },
	]),
	("countersink_hole", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
		ParamSpec { name: "fit", ty: "string", required: false, doc: "" },
		ParamSpec { name: "segments", ty: "int", required: false, doc: "" },
	]),
	("tap_drill_hole", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
		ParamSpec { name: "depth", ty: "number", required: false, doc: "Full-diameter depth of a blind pilot (exclusive with `through`)." },
		ParamSpec { name: "through", ty: "number", required: false, doc: "Material span of a through pilot (exclusive with `depth`)." },
		ParamSpec { name: "segments", ty: "int", required: false, doc: "" },
	]),
	("bolt_circle", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "center", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "circle_d", ty: "number", required: true, doc: "" },
		ParamSpec { name: "n", ty: "int", required: true, doc: "" },
		ParamSpec { name: "start_deg", ty: "number", required: false, doc: "" },
		ParamSpec { name: "hole", ty: "object", required: true, doc: "" },
		ParamSpec { name: "segments", ty: "int", required: false, doc: "" },
	]),
	("bearing_seat", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "at", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "axis", ty: "[x,y,z]", required: true, doc: "" },
		ParamSpec { name: "bearing", ty: "string", required: true, doc: "Bearing designation: 603, 608, 625, 688, 6000, 6001 or 6804." },
		ParamSpec { name: "segments", ty: "int", required: false, doc: "" },
	]),
	("thread_spec", &[
		ParamSpec { name: "m", ty: "number", required: true, doc: "" },
	]),
	("thread_ridge", &[
		ParamSpec { name: "m", ty: "number", required: false, doc: "Nominal ISO size (M3–M16 coarse); exclusive with `major_d`+`pitch`." },
		ParamSpec { name: "major_d", ty: "number", required: false, doc: "Explicit crest **diameter** (mm); requires `pitch`." },
		ParamSpec { name: "pitch", ty: "number", required: false, doc: "Explicit thread pitch (mm); requires `major_d`." },
		ParamSpec { name: "z0", ty: "number", required: false, doc: "Axial start of the ridge (default 0)." },
		ParamSpec { name: "length", ty: "number", required: true, doc: "Axial span of the ridge (`length/pitch` turns, capped at 200)." },
	]),
	("export_threaded", &[
		ParamSpec { name: "in", ty: "id-ref", required: true, doc: "" },
		ParamSpec { name: "m", ty: "number", required: true, doc: "Nominal ISO size (M3–M16, coarse pitch)." },
		ParamSpec { name: "z0", ty: "number", required: false, doc: "Axial start of the threaded span (default 0)." },
		ParamSpec { name: "length", ty: "number", required: true, doc: "Axial span of the thread (`length/pitch` turns, capped at 200)." },
		ParamSpec { name: "internal", ty: "bool", required: false, doc: "Cut a female thread into a bore instead of fusing a male one (default false)." },
		ParamSpec { name: "voxel", ty: "number", required: false, doc: "Voxel size (mm); default pitch/8." },
		ParamSpec { name: "file", ty: "string", required: true, doc: "Output mesh path — the extension picks the format (`.stl` / `.3mf`)." },
	]),
];

/// The parameter specs of one op by wire tag (`None` for an unknown tag) — the lookup behind
/// `describe {name}`.
pub fn op_params(name: &str) -> Option<&'static [ParamSpec]> {
	OP_PARAMS.iter().find(|(tag, _)| *tag == name).map(|(_, specs)| *specs)
}
