// Copyright (c) LMCAD. Licensed under the MIT License.

//! Curated, admission-gated **parts library** (BAR.md, I7) — the growing,
//! AI-extensible catalog of `.lmcpart` entries.
//!
//! A [`Library`] is a plain directory: one `.lmcpart` file per admitted entry
//! plus a byte-stable `index.json` (every JSON object written with sorted keys,
//! entries sorted by `(name, version)`), so the whole library is git-versioned
//! data — every admission, deprecation and removal is auditable and reversible
//! through ordinary version control.
//!
//! ## The admission gate (no pollution)
//! [`Library::add`] accepts a candidate part ONLY after it proves itself at a
//! deterministic sample set of its **declared parameter interface**
//! ([`ParamSpec`]: units / default / min / max per parameter):
//!
//! - the **defaults** sample, every **range corner** (all `2^n` min/max
//!   combinations, capped — default 16 — by a deterministic spread that always
//!   keeps all-min, all-max and each single-parameter extreme), and the
//!   **midpoint**;
//! - each sample must rebuild to a **closed manifold** B-rep, and rebuild
//!   **volume-bit-deterministically** (two full evaluations must agree to the
//!   last bit);
//! - per-sample measures (volume, face count, genus, shells) are recorded in
//!   the entry's [`GateSummary`] as evidence.
//!
//! A failing candidate is rejected with a loud [`AdmissionError`] naming the
//! exact failing sample and its parameter values — never a silent skip. Honest
//! scope: the gate proves validity and determinism **at the sampled points**,
//! not across the whole continuous range between them.
//!
//! ## Curation lifecycle (user and AI share control)
//! - [`Library::search`] finds entries by free text and tags; **deprecated
//!   entries are hidden** from search.
//! - [`Library::instantiate`] builds a fresh [`Document`] from a stored entry
//!   with caller parameters, loudly rejecting unknown names/versions, unknown
//!   parameters and out-of-range values. A deprecated entry still instantiates
//!   (existing designs keep building) but the result **warns** via
//!   [`Instantiated::deprecated`].
//! - [`Library::deprecate`] hides a name from search without touching files.
//! - [`Library::remove`] deletes a name's files and index rows, but **refuses
//!   with the dependent list** ([`LibraryError::DependentsExist`]) when any
//!   `.lmcasm` in the directory still references one of them by path — unless
//!   `force` is passed (git history keeps the removal recoverable).
//!
//! Dates are **caller-supplied** ([`Provenance::date`]): this module never
//! reads a clock, so identical inputs always produce identical bytes.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::path::{Component, Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::format::{self, FormatError};
use crate::Document;

/// The `format` tag of a library `index.json`.
pub const LIBRARY_INDEX_FORMAT: &str = "lmc-library-index";
/// The (single) index version this kernel writes and reads.
pub const LIBRARY_INDEX_VERSION: u32 = 1;
/// File name of the index inside the library directory.
pub const INDEX_FILE: &str = "index.json";
/// How many full rebuilds the admission gate compares for bit-determinism.
pub const GATE_REBUILDS: u32 = 2;

/// One declared parameter of an entry's public interface: the name an
/// [`Library::instantiate`] caller may set, its units, its default and its
/// admissible `[min, max]` range (both inclusive; `min == max` pins it).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParamSpec {
	/// Parameter name — must exist in the part document's parameter table.
	pub name: String,
	/// Units of the value (`"mm"`, `"deg"`, `"count"`, …); declared, not converted.
	pub units: String,
	/// The default value, used for unset parameters on instantiate.
	pub default: f64,
	/// Inclusive lower bound of admissible values.
	pub min: f64,
	/// Inclusive upper bound of admissible values.
	pub max: f64,
	/// What the parameter means (may be empty).
	#[serde(default)]
	pub description: String,
}

/// Who/what authored an entry and when. The `date` is **supplied by the
/// caller** (e.g. `"2026-06-10"`) — the library never reads a clock, keeping
/// every write reproducible byte-for-byte.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Provenance {
	/// Who authored the part (a person, an AI session, a pipeline id).
	pub author: String,
	/// What produced the part file (tool + version).
	pub created_with: String,
	/// Caller-supplied creation date string; never generated by this module.
	pub date: String,
}

/// The caller-supplied metadata of a candidate entry for [`Library::add`].
#[derive(Clone, Debug, PartialEq)]
pub struct EntryMeta {
	/// Library name of the part (also the stored file stem):
	/// 1–64 chars of `A–Z a–z 0–9 . _ -`, starting alphanumeric.
	pub name: String,
	/// Version of this entry, `≥ 1`. One `(name, version)` is immutable once
	/// admitted; changed geometry must be admitted as a new version.
	pub version: u32,
	/// Coarse grouping for search (`"bearings"`, `"brackets"`, …; may be empty).
	pub category: String,
	/// Search tags (sorted + deduplicated on admission).
	pub tags: Vec<String>,
	/// Free-text description (searched).
	pub description: String,
	/// Authorship record; `date` comes from the caller, never from a clock.
	pub provenance: Provenance,
	/// The declared public parameter interface (may be empty for a fixed part).
	pub param_interface: Vec<ParamSpec>,
}

/// Options of [`Library::add`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AddOptions {
	/// Maximum number of range-corner samples the gate builds (`≥ 2`; default
	/// 16). With `n` interface parameters the gate uses all `2^n` corners when
	/// they fit, else a deterministic spread of `corner_cap` corners that always
	/// contains all-min, all-max, and each single-parameter extreme (parameters
	/// beyond the cap's reach are still exercised by all-min/all-max).
	pub corner_cap: usize,
}

impl Default for AddOptions {
	fn default() -> Self {
		AddOptions { corner_cap: 16 }
	}
}

/// The recorded measures of one admission-gate sample.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GateSample {
	/// `"defaults"`, `"midpoint"`, or `"corner_<l|h per parameter>"` (interface
	/// order; `l` = min, `h` = max).
	pub label: String,
	/// The exact parameter values of this sample.
	pub params: BTreeMap<String, f64>,
	/// Mesh-faceted enclosed volume of the rebuilt solid (bit-identical across
	/// the gate's rebuilds — that is what the gate proved).
	pub volume: f64,
	/// Face count of the rebuilt solid.
	pub faces: usize,
	/// Genus of the rebuilt solid.
	pub genus: i64,
	/// Shell count of the rebuilt solid.
	pub shells: usize,
}

/// The evidence an entry passed admission: which samples were built and what
/// they measured. `rebuilds` is the number of full evaluations compared for
/// volume-bit-determinism (always [`GATE_REBUILDS`]).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GateSummary {
	/// Full rebuilds compared per sample (volume bits must match exactly).
	pub rebuilds: u32,
	/// The corner cap the gate ran with (see [`AddOptions::corner_cap`]).
	pub corner_cap: usize,
	/// Every sample built, in gate order (defaults, corners, midpoint).
	pub samples: Vec<GateSample>,
}

/// One admitted library entry, exactly as stored in `index.json`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Entry {
	/// Library name (see [`EntryMeta::name`]).
	pub name: String,
	/// Version (see [`EntryMeta::version`]).
	pub version: u32,
	/// Coarse grouping for search.
	pub category: String,
	/// Search tags, sorted and deduplicated.
	pub tags: Vec<String>,
	/// Free-text description.
	pub description: String,
	/// Authorship record (caller-supplied date).
	pub provenance: Provenance,
	/// The declared public parameter interface.
	pub param_interface: Vec<ParamSpec>,
	/// The admission-gate evidence this entry was accepted on.
	pub admitted: GateSummary,
	/// The stored `.lmcpart` file name, relative to the library directory.
	pub file: String,
	/// Whether the entry is deprecated (hidden from search; instantiate warns).
	#[serde(default, skip_serializing_if = "std::ops::Not::not")]
	pub deprecated: bool,
}

/// A successful [`Library::instantiate`]: the rebuilt parametric [`Document`]
/// plus what it was built from. `deprecated` is the **warning channel**
/// required by BAR.md I7 — a deprecated entry still builds, but the caller is
/// told so it can surface the warning instead of silently shipping a part the
/// curators retired.
#[derive(Clone, Debug)]
pub struct Instantiated {
	/// The part document: interface defaults applied, then the caller's values.
	pub document: Document,
	/// The entry's name.
	pub name: String,
	/// The entry version that was instantiated.
	pub version: u32,
	/// True when the entry is deprecated — the build is fine, but warn the user.
	pub deprecated: bool,
}

// --- Errors --------------------------------------------------------------------------

/// Why [`Library::add`] refused a candidate. Every variant names exactly what
/// is wrong; gate failures name the failing **sample** (label + parameter
/// values) so the author can reproduce it.
#[derive(Debug)]
pub enum AdmissionError {
	/// The metadata is malformed: bad name, version 0, inconsistent ranges,
	/// an interface parameter the document does not declare, … (the reason
	/// string is precise).
	BadMeta {
		/// What exactly is malformed.
		reason: String,
	},
	/// This `(name, version)` is already admitted — entries are immutable;
	/// admit changed geometry as a new version.
	DuplicateEntry {
		/// The colliding name.
		name: String,
		/// The colliding version.
		version: u32,
	},
	/// The candidate `part_json` is not a loadable `.lmcpart`.
	BadPart {
		/// The underlying format error.
		error: FormatError,
	},
	/// A gate sample failed to build: the feature tree produced no exact B-rep
	/// (or an empty solid) at those parameter values.
	GateBuildFailed {
		/// The failing sample: label plus its exact parameter values.
		sample: String,
		/// Why the build failed.
		reason: String,
	},
	/// A gate sample built but is not a closed manifold.
	GateInvalid {
		/// The failing sample: label plus its exact parameter values.
		sample: String,
		/// Whether the rebuilt boundary was closed.
		closed: bool,
		/// Whether the rebuilt boundary was manifold.
		manifold: bool,
		/// Genus of the rebuilt boundary.
		genus: i64,
		/// Shell count of the rebuilt boundary.
		shells: usize,
	},
	/// A gate sample did not rebuild volume-bit-deterministically: two full
	/// evaluations disagreed.
	GateNondeterministic {
		/// The failing sample: label plus its exact parameter values.
		sample: String,
		/// Volume of the first build.
		first_volume: f64,
		/// Volume of the second build.
		second_volume: f64,
	},
	/// A library file could not be written (the gate may already have passed;
	/// nothing was admitted).
	Io {
		/// The path that failed.
		path: PathBuf,
		/// The underlying I/O error.
		error: std::io::Error,
	},
}

impl fmt::Display for AdmissionError {
	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
		match self {
			AdmissionError::BadMeta { reason } => write!(f, "bad entry metadata: {reason}"),
			AdmissionError::DuplicateEntry { name, version } => {
				write!(f, "'{name}' v{version} is already admitted — entries are immutable, admit the change as a new version")
			}
			AdmissionError::BadPart { error } => write!(f, "candidate is not a loadable .lmcpart: {error}"),
			AdmissionError::GateBuildFailed { sample, reason } => {
				write!(f, "admission gate: sample {sample} failed to build: {reason}")
			}
			AdmissionError::GateInvalid { sample, closed, manifold, genus, shells } => {
				write!(
					f,
					"admission gate: sample {sample} is not a closed manifold (closed={closed} manifold={manifold} genus={genus} shells={shells})"
				)
			}
			AdmissionError::GateNondeterministic { sample, first_volume, second_volume } => {
				write!(
					f,
					"admission gate: sample {sample} did not rebuild bit-deterministically (volume {first_volume:?} vs {second_volume:?})"
				)
			}
			AdmissionError::Io { path, error } => write!(f, "cannot write library file '{}': {error}", path.display()),
		}
	}
}

impl std::error::Error for AdmissionError {
	fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
		match self {
			AdmissionError::BadPart { error } => Some(error),
			AdmissionError::Io { error, .. } => Some(error),
			_ => None,
		}
	}
}

/// Why a library operation (open / instantiate / deprecate / remove) failed.
#[derive(Debug)]
pub enum LibraryError {
	/// A library file could not be read or written.
	Io {
		/// The path that failed.
		path: PathBuf,
		/// The underlying I/O error.
		error: std::io::Error,
	},
	/// `index.json` exists but is not a loadable library index (wrong format
	/// tag, unsupported version, duplicate entries, unsafe file names, or not
	/// JSON at all).
	IndexCorrupt {
		/// The index path.
		path: PathBuf,
		/// What exactly is wrong.
		reason: String,
	},
	/// No entry with this name exists; lists what does.
	UnknownPart {
		/// The requested name.
		name: String,
		/// All names the library currently holds (sorted, deduplicated).
		available: Vec<String>,
	},
	/// The name exists, but not at the requested version; lists its versions.
	UnknownVersion {
		/// The requested name.
		name: String,
		/// The requested version.
		version: u32,
		/// The versions that exist for this name (ascending).
		available: Vec<u32>,
	},
	/// An instantiate parameter is not part of the entry's declared interface.
	UnknownParam {
		/// The entry being instantiated.
		part: String,
		/// The offending parameter name.
		param: String,
		/// The declared interface parameter names (interface order).
		interface: Vec<String>,
	},
	/// An instantiate value is outside the declared `[min, max]` range (or not
	/// finite).
	OutOfRange {
		/// The entry being instantiated.
		part: String,
		/// The offending parameter name.
		param: String,
		/// The offending value.
		value: f64,
		/// Declared inclusive minimum.
		min: f64,
		/// Declared inclusive maximum.
		max: f64,
	},
	/// A stored `.lmcpart` failed to load back (the directory was edited by
	/// hand or corrupted).
	BadStoredPart {
		/// The stored part path.
		path: PathBuf,
		/// The underlying format error.
		error: FormatError,
	},
	/// A `.lmcasm` in the library directory could not be checked for
	/// dependencies (unreadable JSON) — removal refuses rather than guessing.
	AsmUnreadable {
		/// The assembly file path.
		path: PathBuf,
		/// Why it could not be checked.
		reason: String,
	},
	/// [`Library::remove`] refused: these `.lmcasm` files (relative to the
	/// library directory, sorted) still reference the entry's part files by
	/// path. Pass `force: true` to remove anyway (git history keeps the
	/// removal recoverable).
	DependentsExist {
		/// The name being removed.
		name: String,
		/// The referencing `.lmcasm` file names.
		dependents: Vec<String>,
	},
}

impl fmt::Display for LibraryError {
	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
		match self {
			LibraryError::Io { path, error } => write!(f, "cannot access '{}': {error}", path.display()),
			LibraryError::IndexCorrupt { path, reason } => {
				write!(f, "'{}' is not a loadable library index: {reason}", path.display())
			}
			LibraryError::UnknownPart { name, available } => {
				write!(
					f,
					"no library entry named '{name}' (available: {})",
					if available.is_empty() { "none".to_string() } else { available.join(", ") }
				)
			}
			LibraryError::UnknownVersion { name, version, available } => {
				let versions: Vec<String> = available.iter().map(|v| format!("v{v}")).collect();
				write!(f, "'{name}' has no version {version} (available: {})", versions.join(", "))
			}
			LibraryError::UnknownParam { part, param, interface } => {
				write!(
					f,
					"'{part}' declares no parameter '{param}' (interface: {})",
					if interface.is_empty() { "none — this entry takes no parameters".to_string() } else { interface.join(", ") }
				)
			}
			LibraryError::OutOfRange { part, param, value, min, max } => {
				write!(f, "'{part}' parameter '{param}': {value} is outside the declared range [{min}, {max}]")
			}
			LibraryError::BadStoredPart { path, error } => {
				write!(f, "stored part '{}' failed to load: {error}", path.display())
			}
			LibraryError::AsmUnreadable { path, reason } => {
				write!(f, "cannot check '{}' for dependents: {reason}", path.display())
			}
			LibraryError::DependentsExist { name, dependents } => {
				write!(
					f,
					"refusing to remove '{name}': referenced by {} (pass force to remove anyway; git history keeps it recoverable)",
					dependents.join(", ")
				)
			}
		}
	}
}

impl std::error::Error for LibraryError {
	fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
		match self {
			LibraryError::Io { error, .. } => Some(error),
			LibraryError::BadStoredPart { error, .. } => Some(error),
			_ => None,
		}
	}
}

// --- The index file ---------------------------------------------------------------------

/// Serde mirror of `index.json` (the contract fields are `Option` so a foreign
/// file reports "missing" precisely).
#[derive(Serialize, Deserialize)]
struct IndexFile {
	format: Option<String>,
	version: Option<u32>,
	#[serde(default)]
	entries: Vec<Entry>,
}

/// Serialize `value` with **every JSON object's keys sorted** (serde_json's
/// default `Map` is a `BTreeMap`, so routing through a `Value` canonicalizes
/// key order) — the byte-stable form all library writes use. All floats are
/// validated finite before they get here.
fn canonical_json<T: Serialize>(value: &T) -> String {
	let v = serde_json::to_value(value).expect("library data serializes: string keys, finite floats");
	serde_json::to_string_pretty(&v).expect("a serde_json::Value pretty-prints")
}

// --- The library ---------------------------------------------------------------------------

/// A curated parts library on disk: a directory of admitted `.lmcpart` files
/// plus a byte-stable `index.json`. See the [module docs](self) for the
/// admission gate and the curation lifecycle.
pub struct Library {
	dir: PathBuf,
	/// All entries, sorted by `(name, version)` — including deprecated ones.
	entries: Vec<Entry>,
}

impl Library {
	/// Open the library at `dir`, creating the directory if needed. A missing
	/// `index.json` is an empty library; a present but unreadable/foreign one is
	/// a loud [`LibraryError::IndexCorrupt`] (never half-loads). Hand-edited
	/// indexes are checked: duplicate `(name, version)` rows and `file` fields
	/// that are not plain file names (no `/`, no `..`) are refused.
	pub fn open(dir: impl AsRef<Path>) -> Result<Library, LibraryError> {
		let dir = dir.as_ref().to_path_buf();
		std::fs::create_dir_all(&dir).map_err(|error| LibraryError::Io { path: dir.clone(), error })?;
		let index_path = dir.join(INDEX_FILE);
		let mut entries = match std::fs::read_to_string(&index_path) {
			Err(e) if e.kind() == std::io::ErrorKind::NotFound => Vec::new(),
			Err(error) => return Err(LibraryError::Io { path: index_path, error }),
			Ok(text) => {
				let corrupt = |reason: String| LibraryError::IndexCorrupt { path: index_path.clone(), reason };
				let file: IndexFile = serde_json::from_str(&text).map_err(|e| corrupt(e.to_string()))?;
				match file.format.as_deref() {
					Some(LIBRARY_INDEX_FORMAT) => {}
					found => return Err(corrupt(format!("expected format \"{LIBRARY_INDEX_FORMAT}\", found {found:?}"))),
				}
				if file.version != Some(LIBRARY_INDEX_VERSION) {
					return Err(corrupt(format!("expected version {LIBRARY_INDEX_VERSION}, found {:?}", file.version)));
				}
				let mut seen = BTreeSet::new();
				for entry in &file.entries {
					if !seen.insert((entry.name.clone(), entry.version)) {
						return Err(corrupt(format!("duplicate entry '{}' v{}", entry.name, entry.version)));
					}
					let mut components = Path::new(&entry.file).components();
					let plain = matches!(components.next(), Some(Component::Normal(_))) && components.next().is_none();
					if !plain {
						return Err(corrupt(format!(
							"entry '{}' v{}: file '{}' is not a plain file name inside the library directory",
							entry.name, entry.version, entry.file
						)));
					}
				}
				file.entries
			}
		};
		entries.sort_by(|a, b| (a.name.as_str(), a.version).cmp(&(b.name.as_str(), b.version)));
		Ok(Library { dir, entries })
	}

	/// The directory this library lives in.
	pub fn dir(&self) -> &Path {
		&self.dir
	}

	/// Every entry — **including deprecated ones** — sorted by `(name, version)`.
	/// Use [`Library::search`] for the curated (deprecation-hidden) view.
	pub fn entries(&self) -> &[Entry] {
		&self.entries
	}

	/// Resolve `name` (at `version`, or the **highest admitted version** when
	/// `None`) to its entry. Loud: an unknown name lists the available names, an
	/// unknown version lists the name's versions.
	pub fn entry(&self, name: &str, version: Option<u32>) -> Result<&Entry, LibraryError> {
		let of_name: Vec<&Entry> = self.entries.iter().filter(|e| e.name == name).collect();
		if of_name.is_empty() {
			let mut available: Vec<String> = self.entries.iter().map(|e| e.name.clone()).collect();
			available.dedup(); // entries are sorted by name
			return Err(LibraryError::UnknownPart { name: name.to_string(), available });
		}
		match version {
			// Entries are sorted by (name, version): the last one is the highest.
			None => Ok(of_name[of_name.len() - 1]),
			Some(v) => of_name.iter().find(|e| e.version == v).copied().ok_or_else(|| LibraryError::UnknownVersion {
				name: name.to_string(),
				version: v,
				available: of_name.iter().map(|e| e.version).collect(),
			}),
		}
	}

	/// Admit a candidate part. `part_json` is the full `.lmcpart` envelope text
	/// (see [`format::load_part`]); `meta` declares identity, provenance and the
	/// parameter interface. The candidate must pass the **admission gate** (see
	/// the [module docs](self)): build closed+manifold and volume-bit-
	/// deterministic at the defaults, every sampled range corner, and the
	/// midpoint. On success the part is stored canonically (re-serialized via
	/// [`format::save_part`], byte-stable) as `<name>-v<version>.lmcpart`, the
	/// index is rewritten, and the new [`Entry`] is returned. On failure NOTHING
	/// is admitted and the error names the exact problem — including, for gate
	/// failures, the failing sample's parameter values.
	pub fn add(&mut self, part_json: &str, meta: EntryMeta, opts: &AddOptions) -> Result<&Entry, AdmissionError> {
		let (document, _part_meta) = format::load_part(part_json).map_err(|error| AdmissionError::BadPart { error })?;
		validate_meta(&meta, &document, opts)?;
		if self.entries.iter().any(|e| e.name == meta.name && e.version == meta.version) {
			return Err(AdmissionError::DuplicateEntry { name: meta.name, version: meta.version });
		}

		let samples = run_gate(&document, &meta.param_interface, opts.corner_cap)?;

		let file = format!("{}-v{}.lmcpart", meta.name, meta.version);
		let part_path = self.dir.join(&file);
		// Canonical storage: re-serialized through the byte-stable saver, named
		// by the library identity (the envelope name a search/instantiate sees).
		std::fs::write(&part_path, format::save_part(&document, &meta.name))
			.map_err(|error| AdmissionError::Io { path: part_path.clone(), error })?;

		let mut tags = meta.tags;
		tags.sort();
		tags.dedup();
		let entry = Entry {
			name: meta.name,
			version: meta.version,
			category: meta.category,
			tags,
			description: meta.description,
			provenance: meta.provenance,
			param_interface: meta.param_interface,
			admitted: GateSummary { rebuilds: GATE_REBUILDS, corner_cap: opts.corner_cap, samples },
			file,
			deprecated: false,
		};
		let position = self.entries.partition_point(|e| (e.name.as_str(), e.version) < (entry.name.as_str(), entry.version));
		self.entries.insert(position, entry);
		if let Err((path, error)) = self.write_index() {
			// Keep memory consistent with disk: the entry is NOT admitted (the
			// orphaned part file is harmless and overwritten by a retry).
			self.entries.remove(position);
			return Err(AdmissionError::Io { path, error });
		}
		Ok(&self.entries[position])
	}

	/// Search the curated view: entries whose name/category/description/tags
	/// contain `text` (case-insensitive; empty matches all) AND carry every tag
	/// in `tags` (case-insensitive). **Deprecated entries are hidden** — resolve
	/// them explicitly via [`Library::entry`] / [`Library::instantiate`].
	/// Results keep the `(name, version)` order.
	pub fn search(&self, text: &str, tags: &[String]) -> Vec<&Entry> {
		let needle = text.to_lowercase();
		self.entries
			.iter()
			.filter(|e| !e.deprecated)
			.filter(|e| {
				let haystack = format!("{} {} {} {}", e.name, e.category, e.description, e.tags.join(" ")).to_lowercase();
				needle.is_empty() || haystack.contains(&needle)
			})
			.filter(|e| {
				tags.iter().all(|want| {
					let want = want.to_lowercase();
					e.tags.iter().any(|t| t.to_lowercase() == want)
				})
			})
			.collect()
	}

	/// Instantiate `name` (at `version`, default: highest) with the given
	/// parameter values: the stored part is loaded, the **interface defaults**
	/// are applied first, then the caller's `params` — each checked loudly
	/// against the declared interface ([`LibraryError::UnknownParam`]) and range
	/// ([`LibraryError::OutOfRange`], which also rejects non-finite values).
	/// A deprecated entry still instantiates but sets
	/// [`Instantiated::deprecated`] so the caller can warn. The document is NOT
	/// evaluated here — call [`Document::evaluate_brep`] / [`Document::mesh`]
	/// on the result.
	pub fn instantiate(&self, name: &str, version: Option<u32>, params: &BTreeMap<String, f64>) -> Result<Instantiated, LibraryError> {
		let entry = self.entry(name, version)?;
		let path = self.dir.join(&entry.file);
		let text = std::fs::read_to_string(&path).map_err(|error| LibraryError::Io { path: path.clone(), error })?;
		let (mut document, _) = format::load_part(&text).map_err(|error| LibraryError::BadStoredPart { path, error })?;
		for spec in &entry.param_interface {
			document.set_param(spec.name.clone(), spec.default);
		}
		for (param, &value) in params {
			let spec = entry.param_interface.iter().find(|s| &s.name == param).ok_or_else(|| LibraryError::UnknownParam {
				part: entry.name.clone(),
				param: param.clone(),
				interface: entry.param_interface.iter().map(|s| s.name.clone()).collect(),
			})?;
			// `!(>= && <=)` also rejects NaN/±inf loudly.
			if !(value >= spec.min && value <= spec.max) {
				return Err(LibraryError::OutOfRange {
					part: entry.name.clone(),
					param: param.clone(),
					value,
					min: spec.min,
					max: spec.max,
				});
			}
			document.set_param(param.clone(), value);
		}
		Ok(Instantiated { document, name: entry.name.clone(), version: entry.version, deprecated: entry.deprecated })
	}

	/// Deprecate every version of `name`: hidden from [`Library::search`],
	/// still on disk, still instantiable (with the [`Instantiated::deprecated`]
	/// warning), still resolvable by `.lmcasm` path references. Idempotent;
	/// returns how many versions are now deprecated. Loud on an unknown name.
	pub fn deprecate(&mut self, name: &str) -> Result<usize, LibraryError> {
		self.entry(name, None)?; // loud UnknownPart
		let before: Vec<bool> = self.entries.iter().map(|e| e.deprecated).collect();
		let mut count = 0;
		for entry in self.entries.iter_mut().filter(|e| e.name == name) {
			entry.deprecated = true;
			count += 1;
		}
		if let Err((path, error)) = self.write_index() {
			// Keep memory consistent with disk: the deprecation did not persist.
			for (entry, was) in self.entries.iter_mut().zip(before) {
				entry.deprecated = was;
			}
			return Err(LibraryError::Io { path, error });
		}
		Ok(count)
	}

	/// The `.lmcasm` files in the library directory (names sorted) that
	/// reference any of `name`'s part files by path — the dependents that make
	/// [`Library::remove`] refuse. An `.lmcasm` that cannot be parsed is a loud
	/// [`LibraryError::AsmUnreadable`] (a removal must not guess).
	pub fn dependents(&self, name: &str) -> Result<Vec<String>, LibraryError> {
		let files: BTreeSet<PathBuf> =
			self.entries.iter().filter(|e| e.name == name).map(|e| lexically_normalized(Path::new(&e.file))).collect();
		let read_dir = std::fs::read_dir(&self.dir).map_err(|error| LibraryError::Io { path: self.dir.clone(), error })?;
		let mut asm_files: Vec<PathBuf> = read_dir
			.filter_map(|r| r.ok().map(|d| d.path()))
			.filter(|p| p.extension().and_then(|e| e.to_str()) == Some("lmcasm"))
			.collect();
		asm_files.sort();
		let mut dependents = Vec::new();
		for asm in asm_files {
			let text = std::fs::read_to_string(&asm).map_err(|error| LibraryError::Io { path: asm.clone(), error })?;
			let value: serde_json::Value = serde_json::from_str(&text)
				.map_err(|e| LibraryError::AsmUnreadable { path: asm.clone(), reason: format!("not valid JSON: {e}") })?;
			let instances = value.get("instances").and_then(serde_json::Value::as_array);
			let references = instances.into_iter().flatten().any(|instance| {
				instance
					.get("source")
					.and_then(|s| s.get("path"))
					.and_then(serde_json::Value::as_str)
					.is_some_and(|p| files.contains(&lexically_normalized(Path::new(p))))
			});
			if references {
				dependents.push(asm.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default());
			}
		}
		Ok(dependents)
	}

	/// Remove every version of `name`: deletes the part files and index rows.
	/// Without `force` this first scans the directory's `.lmcasm` files and
	/// **refuses** with [`LibraryError::DependentsExist`] (naming them) when any
	/// still references the part by path. With `force` the scan is skipped and
	/// the removal proceeds — git history keeps it auditable and recoverable.
	/// Returns the removed part file names. Loud on an unknown name. (If the
	/// index rewrite itself fails mid-removal, the deleted files are already
	/// gone — instantiate then fails loudly on the stale row, and the next
	/// successful mutation, or git, restores consistency.)
	pub fn remove(&mut self, name: &str, force: bool) -> Result<Vec<String>, LibraryError> {
		self.entry(name, None)?; // loud UnknownPart
		if !force {
			let dependents = self.dependents(name)?;
			if !dependents.is_empty() {
				return Err(LibraryError::DependentsExist { name: name.to_string(), dependents });
			}
		}
		let removed: Vec<String> = self.entries.iter().filter(|e| e.name == name).map(|e| e.file.clone()).collect();
		for file in &removed {
			let path = self.dir.join(file);
			match std::fs::remove_file(&path) {
				Ok(()) => {}
				// Already gone is fine — the goal is its absence.
				Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
				Err(error) => return Err(LibraryError::Io { path, error }),
			}
		}
		self.entries.retain(|e| e.name != name);
		self.write_index().map_err(|(path, error)| LibraryError::Io { path, error })?;
		Ok(removed)
	}

	/// Rewrite `index.json` (sorted keys, entries sorted by `(name, version)`)
	/// — byte-stable: the same entries always produce identical bytes.
	fn write_index(&self) -> Result<(), (PathBuf, std::io::Error)> {
		let file = IndexFile {
			format: Some(LIBRARY_INDEX_FORMAT.to_string()),
			version: Some(LIBRARY_INDEX_VERSION),
			entries: self.entries.clone(),
		};
		let path = self.dir.join(INDEX_FILE);
		std::fs::write(&path, canonical_json(&file)).map_err(|error| (path.clone(), error))
	}
}

// --- Admission internals ---------------------------------------------------------------------

/// Validate name/version/interface/provenance before anything is built.
fn validate_meta(meta: &EntryMeta, document: &Document, opts: &AddOptions) -> Result<(), AdmissionError> {
	let bad = |reason: String| Err(AdmissionError::BadMeta { reason });
	let name_ok = !meta.name.is_empty()
		&& meta.name.len() <= 64
		&& meta.name.chars().next().is_some_and(|c| c.is_ascii_alphanumeric())
		&& meta.name.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'));
	if !name_ok {
		return bad(format!(
			"name '{}' — must be 1–64 chars of A–Z a–z 0–9 . _ - and start alphanumeric (it becomes the stored file name)",
			meta.name
		));
	}
	if meta.version == 0 {
		return bad("version must be ≥ 1".to_string());
	}
	if opts.corner_cap < 2 {
		return bad(format!("corner_cap {} — the gate needs at least the all-min and all-max corners (≥ 2)", opts.corner_cap));
	}
	if meta.provenance.author.is_empty() || meta.provenance.date.is_empty() || meta.provenance.created_with.is_empty() {
		return bad(
			"provenance author/created_with/date must all be non-empty (the date is caller-supplied; this library never reads a clock)"
				.to_string(),
		);
	}
	let document_params: BTreeSet<&str> = document.params_iter().map(|(k, _)| k).collect();
	let mut seen = BTreeSet::new();
	for spec in &meta.param_interface {
		if spec.name.is_empty() {
			return bad("param_interface contains an empty parameter name".to_string());
		}
		if !seen.insert(spec.name.as_str()) {
			return bad(format!("param_interface declares '{}' twice", spec.name));
		}
		if spec.units.is_empty() {
			return bad(format!("parameter '{}': units must be declared (\"mm\", \"deg\", \"count\", …)", spec.name));
		}
		if !(spec.default.is_finite() && spec.min.is_finite() && spec.max.is_finite()) {
			return bad(format!("parameter '{}': default/min/max must all be finite", spec.name));
		}
		if spec.min > spec.max {
			return bad(format!("parameter '{}': min {} > max {}", spec.name, spec.min, spec.max));
		}
		if !(spec.default >= spec.min && spec.default <= spec.max) {
			return bad(format!("parameter '{}': default {} is outside [{}, {}]", spec.name, spec.default, spec.min, spec.max));
		}
		// A typo'd interface name would drive NOTHING (set_param would insert an
		// unused key and every sample would silently build the same shape).
		if !document_params.contains(spec.name.as_str()) {
			return bad(format!(
				"parameter '{}' is not in the part document's parameter table (document declares: {})",
				spec.name,
				if document_params.is_empty() {
					"none".to_string()
				} else {
					document_params.iter().copied().collect::<Vec<_>>().join(", ")
				}
			));
		}
	}
	Ok(())
}

/// The gate's sample plan: defaults, corners (capped), midpoint — deduplicated
/// by parameter values (a `min == max` parameter collapses corners), keeping
/// the first label.
fn gate_samples(interface: &[ParamSpec], corner_cap: usize) -> Vec<(String, BTreeMap<String, f64>)> {
	let mut plan: Vec<(String, BTreeMap<String, f64>)> = Vec::new();
	let push = |label: String, params: BTreeMap<String, f64>, plan: &mut Vec<(String, BTreeMap<String, f64>)>| {
		if !plan.iter().any(|(_, p)| *p == params) {
			plan.push((label, params));
		}
	};
	let defaults: BTreeMap<String, f64> = interface.iter().map(|s| (s.name.clone(), s.default)).collect();
	push("defaults".to_string(), defaults, &mut plan);

	let n = interface.len();
	if n > 0 {
		for corner in corner_masks(n, corner_cap) {
			let label: String = std::iter::once("corner_".to_string())
				.chain(corner.iter().map(|&high| if high { "h".to_string() } else { "l".to_string() }))
				.collect();
			let params: BTreeMap<String, f64> =
				interface.iter().zip(&corner).map(|(s, &high)| (s.name.clone(), if high { s.max } else { s.min })).collect();
			push(label, params, &mut plan);
		}
		let midpoint: BTreeMap<String, f64> = interface.iter().map(|s| (s.name.clone(), 0.5 * (s.min + s.max))).collect();
		push("midpoint".to_string(), midpoint, &mut plan);
	}
	plan
}

/// The corner combinations to sample: all `2^n` when they fit under `cap`,
/// else a deterministic spread of exactly `cap` corners — all-min, all-max,
/// each single parameter flipped high (from all-min) and flipped low (from
/// all-max) in interface order, then a Hamming-weight fill (every pair high,
/// every triple high, … lexicographically) until the cap is reached. The first
/// two corners always exercise every parameter at both extremes; the per-
/// parameter isolation corners cover as many leading parameters as fit.
fn corner_masks(n: usize, cap: usize) -> Vec<Vec<bool>> {
	if n < usize::BITS as usize && (1usize << n) <= cap {
		// Exhaustive: bit j of the counter = parameter j high.
		return (0..1usize << n).map(|mask| (0..n).map(|j| mask >> j & 1 == 1).collect()).collect();
	}
	fn push(mask: Vec<bool>, masks: &mut Vec<Vec<bool>>, cap: usize) {
		if masks.len() < cap && !masks.contains(&mask) {
			masks.push(mask);
		}
	}
	let mut masks: Vec<Vec<bool>> = vec![vec![false; n], vec![true; n]];
	for j in 0..n {
		for base in [false, true] {
			let mut mask = vec![base; n];
			mask[j] = !base;
			push(mask, &mut masks, cap);
		}
	}
	// Fill the remaining budget by Hamming weight: 2^n > cap here, and weights
	// 0..=n enumerate every corner, so the cap is always reached.
	let mut weight = 2;
	while masks.len() < cap && weight < n {
		let mut combo: Vec<usize> = (0..weight).collect();
		loop {
			let mut mask = vec![false; n];
			for &i in &combo {
				mask[i] = true;
			}
			push(mask, &mut masks, cap);
			if masks.len() == cap || !next_combination(&mut combo, n) {
				break;
			}
		}
		weight += 1;
	}
	masks
}

/// Advance `combo` (strictly increasing indices into `0..n`) to the next
/// lexicographic combination; `false` when exhausted.
fn next_combination(combo: &mut [usize], n: usize) -> bool {
	let w = combo.len();
	let mut i = w;
	while i > 0 {
		i -= 1;
		if combo[i] < n - w + i {
			combo[i] += 1;
			for k in i + 1..w {
				combo[k] = combo[k - 1] + 1;
			}
			return true;
		}
	}
	false
}

/// Render a sample for error messages: `label (k=v, …)`.
fn sample_string(label: &str, params: &BTreeMap<String, f64>) -> String {
	if params.is_empty() {
		return label.to_string();
	}
	let body: Vec<String> = params.iter().map(|(k, v)| format!("{k}={v}")).collect();
	format!("{label} ({})", body.join(", "))
}

/// Run the admission gate (see the [module docs](self)) and return the
/// per-sample evidence, or the loud error naming the failing sample.
fn run_gate(document: &Document, interface: &[ParamSpec], corner_cap: usize) -> Result<Vec<GateSample>, AdmissionError> {
	let mut samples = Vec::new();
	for (label, params) in gate_samples(interface, corner_cap) {
		let sample = || sample_string(&label, &params);
		let mut doc = document.clone();
		for (k, &v) in &params {
			doc.set_param(k.clone(), v);
		}
		let mut volumes = [0.0f64; GATE_REBUILDS as usize];
		let mut faces = 0;
		let mut genus = 0;
		let mut shells = 0;
		for volume in &mut volumes {
			// A FULL fresh evaluation each round — the determinism this proves is
			// the rebuild's, not a cache's (a Document caches no geometry).
			let solid = doc.evaluate_brep().ok_or_else(|| AdmissionError::GateBuildFailed {
				sample: sample(),
				reason: "the feature tree produced no exact B-rep at these values (missing feature, cyclic reference, or a voxel-half-only feature)".to_string(),
			})?;
			if solid.face_count() == 0 {
				return Err(AdmissionError::GateBuildFailed {
					sample: sample(),
					reason: "the rebuild produced an EMPTY solid — the dimensions degenerate at these values (e.g. a cut consumes the whole body)".to_string(),
				});
			}
			let validity = kernel_brep::validate(&solid);
			if !(validity.closed && validity.manifold) {
				return Err(AdmissionError::GateInvalid {
					sample: sample(),
					closed: validity.closed,
					manifold: validity.manifold,
					genus: validity.genus,
					shells: validity.shells,
				});
			}
			*volume = kernel_brep::volume(&solid);
			if !volume.is_finite() {
				return Err(AdmissionError::GateBuildFailed {
					sample: sample(),
					reason: format!("the rebuild's volume is not finite ({volume})"),
				});
			}
			faces = solid.face_count();
			genus = validity.genus;
			shells = validity.shells;
		}
		if let Some(&second) = volumes.iter().find(|v| v.to_bits() != volumes[0].to_bits()) {
			return Err(AdmissionError::GateNondeterministic { sample: sample(), first_volume: volumes[0], second_volume: second });
		}
		samples.push(GateSample { label, params, volume: volumes[0], faces, genus, shells });
	}
	Ok(samples)
}

/// Lexically normalize a relative path: drop `.` components and resolve `..`
/// against preceding components (purely textual — no filesystem access), so
/// `"./x.lmcpart"` and `"sub/../x.lmcpart"` both compare equal to
/// `"x.lmcpart"` in the dependents scan.
fn lexically_normalized(path: &Path) -> PathBuf {
	let mut out = PathBuf::new();
	for component in path.components() {
		match component {
			Component::CurDir => {}
			Component::ParentDir => {
				if !out.pop() {
					out.push("..");
				}
			}
			other => out.push(other),
		}
	}
	out
}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::{BooleanOp, Dim, Feature};

	/// A unique per-test library directory under the system temp dir.
	fn test_dir(name: &str) -> PathBuf {
		let dir = std::env::temp_dir().join(format!("lmcad_library_{name}_{}", std::process::id()));
		let _ = std::fs::remove_dir_all(&dir);
		dir
	}

	/// The reference candidate: a bushing — outer cylinder minus a through bore,
	/// driven by `outer_r` / `bore_r` / `h` (all declared in the params table).
	fn bushing_part_json() -> String {
		let mut doc = Document::new();
		doc.set_param("outer_r", 12.0);
		doc.set_param("bore_r", 4.0);
		doc.set_param("h", 10.0);
		let outer = doc.add(Feature::Cylinder {
			center: [Dim::Literal(0.0), Dim::Literal(0.0), Dim::Literal(0.0)],
			radius: Dim::param("outer_r"),
			height: Dim::param("h"),
		});
		let bore = doc.add(Feature::Cylinder {
			center: [Dim::Literal(0.0), Dim::Literal(0.0), Dim::Literal(0.0)],
			radius: Dim::param("bore_r"),
			// Tall literal tool: through for every admissible h.
			height: Dim::Literal(200.0),
		});
		let cut = doc.add(Feature::Boolean { op: BooleanOp::Difference, a: outer, b: bore });
		doc.set_root(cut);
		format::save_part(&doc, "bushing")
	}

	fn bushing_meta() -> EntryMeta {
		EntryMeta {
			name: "bushing".to_string(),
			version: 1,
			category: "spacers".to_string(),
			tags: vec!["sleeve".to_string(), "Bearing".to_string(), "sleeve".to_string()],
			description: "parametric plain bushing with a through bore".to_string(),
			provenance: Provenance {
				author: "unit-test".to_string(),
				created_with: "kernel-model tests".to_string(),
				// Caller-supplied — the library never reads a clock.
				date: "2026-06-10".to_string(),
			},
			param_interface: vec![
				ParamSpec {
					name: "outer_r".to_string(),
					units: "mm".to_string(),
					default: 12.0,
					min: 8.0,
					max: 16.0,
					description: "outer radius".to_string(),
				},
				ParamSpec {
					name: "bore_r".to_string(),
					units: "mm".to_string(),
					default: 4.0,
					min: 2.0,
					max: 5.0,
					description: "bore radius".to_string(),
				},
				ParamSpec {
					name: "h".to_string(),
					units: "mm".to_string(),
					default: 10.0,
					min: 4.0,
					max: 40.0,
					description: "height".to_string(),
				},
			],
		}
	}

	/// Admission: the 3-parameter bushing runs the FULL gate (defaults + 2³
	/// corners + midpoint = 10 samples, 2 rebuilds each), records per-sample
	/// measures, stores a canonical part file, and the index round-trips
	/// byte-stably (a second open + an add/remove cycle rewrites identical
	/// bytes). Search finds it by text and tag; tags are sorted + deduplicated.
	#[test]
	fn admission_gate_lifecycle_and_byte_stable_index() {
		let dir = test_dir("admit");
		let mut lib = Library::open(&dir).expect("open fresh library");
		let entry = lib.add(&bushing_part_json(), bushing_meta(), &AddOptions::default()).expect("bushing admits").clone();
		let labels: Vec<&str> = entry.admitted.samples.iter().map(|s| s.label.as_str()).collect();
		let defaults_volume = entry.admitted.samples[0].volume;
		// 32-gon annulus closed form: (16 sin(π/16)) (R² − r²) h — the boolean of
		// two aligned polygonal prisms carries no faceting error, only float noise.
		let expected = 16.0 * (std::f64::consts::PI / 16.0).sin() * (144.0 - 16.0) * 10.0;
		let index_bytes_1 = std::fs::read_to_string(dir.join(INDEX_FILE)).expect("index exists");

		// Re-open; admit a second entry and remove it again — the rewritten
		// index must be byte-identical to the first save.
		let mut lib2 = Library::open(&dir).expect("re-open");
		let mut meta2 = bushing_meta();
		meta2.name = "bushing2".to_string();
		lib2.add(&bushing_part_json(), meta2, &AddOptions::default()).expect("second entry admits");
		lib2.remove("bushing2", false).expect("unreferenced entry removes");
		let index_bytes_2 = std::fs::read_to_string(dir.join(INDEX_FILE)).expect("index exists");

		let found = lib2.search("bushing", &["bearing".to_string()]);
		assert!(
			labels == ["defaults", "corner_lll", "corner_hll", "corner_lhl", "corner_hhl", "corner_llh", "corner_hlh", "corner_lhh", "corner_hhh", "midpoint"]
				&& entry.admitted.rebuilds == 2
				&& entry.admitted.samples.iter().all(|s| s.genus == 1 && s.shells == 1 && s.volume > 0.0)
				&& (defaults_volume - expected).abs() < 1e-6 * expected
				&& entry.file == "bushing-v1.lmcpart"
				&& entry.tags == ["Bearing", "sleeve"]
				&& dir.join(&entry.file).exists()
				&& index_bytes_1 == index_bytes_2
				&& found.len() == 1
				&& found[0].version == 1,
			"admission evidence: labels={labels:?} rebuilds={} defaults_volume={defaults_volume} (want {expected}) file={} tags={:?} byte_stable={} search_hits={}",
			entry.admitted.rebuilds,
			entry.file,
			entry.tags,
			index_bytes_1 == index_bytes_2,
			found.len(),
		);
		let _ = std::fs::remove_dir_all(&dir);
	}

	/// Gate rejection: a box with a bore whose declared range reaches r = 15 —
	/// at the high corner the bore swallows the whole 20×20×10 box, the
	/// difference is EMPTY, and admission must refuse LOUDLY, naming the
	/// failing corner and its parameter values, admitting nothing.
	#[test]
	fn gate_rejects_breaking_corner_loudly() {
		let dir = test_dir("reject");
		let mut doc = Document::new();
		doc.set_param("r", 5.0);
		let block = doc.add(Feature::Box {
			center: [Dim::Literal(0.0), Dim::Literal(0.0), Dim::Literal(0.0)],
			size: [Dim::Literal(20.0), Dim::Literal(20.0), Dim::Literal(10.0)],
		});
		let bore = doc.add(Feature::Cylinder {
			center: [Dim::Literal(0.0), Dim::Literal(0.0), Dim::Literal(0.0)],
			radius: Dim::param("r"),
			height: Dim::Literal(50.0),
		});
		let cut = doc.add(Feature::Boolean { op: BooleanOp::Difference, a: block, b: bore });
		doc.set_root(cut);
		let mut meta = bushing_meta();
		meta.name = "overdrilled".to_string();
		meta.param_interface = vec![ParamSpec {
			name: "r".to_string(),
			units: "mm".to_string(),
			default: 5.0,
			min: 2.0,
			max: 15.0, // > the box's half-diagonal 14.14 — the high corner empties the part
			description: "bore radius".to_string(),
		}];
		let mut lib = Library::open(&dir).expect("open");
		let err = lib.add(&format::save_part(&doc, "overdrilled"), meta, &AddOptions::default()).expect_err("high corner must reject");
		let message = err.to_string();
		assert!(
			matches!(err, AdmissionError::GateBuildFailed { .. })
				&& message.contains("corner_h")
				&& message.contains("r=15")
				&& message.contains("EMPTY")
				&& lib.entries().is_empty()
				&& !dir.join("overdrilled-v1.lmcpart").exists()
				&& !dir.join(INDEX_FILE).exists(),
			"gate rejection must name the corner, admit nothing, write nothing: err={message} entries={}",
			lib.entries().len()
		);
		let _ = std::fs::remove_dir_all(&dir);
	}

	/// Metadata validation is loud: traversal-shaped names, version 0, an
	/// interface parameter the document does not declare, min > max, an
	/// out-of-range default, a duplicate (name, version), empty provenance —
	/// each a precise BadMeta/DuplicateEntry, never a fallback.
	#[test]
	fn bad_meta_paths_are_loud() {
		let dir = test_dir("badmeta");
		let mut lib = Library::open(&dir).expect("open");
		let part = bushing_part_json();
		fn reason(lib: &mut Library, part: &str, meta: EntryMeta) -> String {
			match lib.add(part, meta, &AddOptions::default()) {
				Err(e) => e.to_string(),
				Ok(entry) => panic!("must refuse, admitted {} v{}", entry.name, entry.version),
			}
		}

		let mut traversal = bushing_meta();
		traversal.name = "../escape".to_string();
		let mut zero = bushing_meta();
		zero.version = 0;
		let mut ghost = bushing_meta();
		ghost.param_interface[0].name = "diamter".to_string(); // typo: not a document param
		let mut inverted = bushing_meta();
		inverted.param_interface[1].min = 9.0; // > max 5
		let mut stray_default = bushing_meta();
		stray_default.param_interface[2].default = 99.0; // outside [4, 40]
		let mut dateless = bushing_meta();
		dateless.provenance.date = String::new();

		let messages = [
			reason(&mut lib, &part, traversal),
			reason(&mut lib, &part, zero),
			reason(&mut lib, &part, ghost),
			reason(&mut lib, &part, inverted),
			reason(&mut lib, &part, stray_default),
			reason(&mut lib, &part, dateless),
		];
		lib.add(&part, bushing_meta(), &AddOptions::default()).expect("the honest meta admits");
		let duplicate = reason(&mut lib, &part, bushing_meta());
		assert!(
			messages[0].contains("'../escape'")
				&& messages[1].contains("version")
				&& messages[2].contains("'diamter'")
				&& messages[3].contains("min 9 > max 5")
				&& messages[4].contains("default 99")
				&& messages[5].contains("date")
				&& duplicate.contains("'bushing' v1 is already admitted"),
			"every bad-meta path must be loud and precise: {messages:#?} duplicate={duplicate}"
		);
		let _ = std::fs::remove_dir_all(&dir);
	}

	/// Instantiate semantics: defaults first, overrides on top; unknown
	/// parameter and out-of-range (incl. NaN) values are loud; unknown name
	/// lists what exists; unknown version lists the name's versions; a
	/// deprecated entry STILL instantiates but carries the warning flag, and is
	/// hidden from search.
	#[test]
	fn instantiate_and_deprecation_semantics() {
		let dir = test_dir("instantiate");
		let mut lib = Library::open(&dir).expect("open");
		lib.add(&bushing_part_json(), bushing_meta(), &AddOptions::default()).expect("admit");

		let built = lib.instantiate("bushing", None, &BTreeMap::from([("h".to_string(), 20.0)])).expect("override h within range");
		let (h, outer_r) = (built.document.param("h"), built.document.param("outer_r"));

		let unknown_param = lib.instantiate("bushing", None, &BTreeMap::from([("hh".to_string(), 20.0)])).expect_err("unknown param");
		let out_of_range = lib.instantiate("bushing", None, &BTreeMap::from([("h".to_string(), 41.0)])).expect_err("41 > max 40");
		let nan = lib.instantiate("bushing", None, &BTreeMap::from([("h".to_string(), f64::NAN)])).expect_err("NaN");
		let unknown_part = lib.instantiate("flange", None, &BTreeMap::new()).expect_err("unknown name");
		let unknown_version = lib.instantiate("bushing", Some(9), &BTreeMap::new()).expect_err("unknown version");

		let deprecated_count = lib.deprecate("bushing").expect("deprecate");
		let hidden = lib.search("", &[]);
		let warned = lib.instantiate("bushing", None, &BTreeMap::new()).expect("deprecated still builds");
		let volume = warned.document.evaluate_brep().map(|s| kernel_brep::volume(&s)).unwrap_or(f64::NAN);

		assert!(
			h == Some(20.0)
				&& outer_r == Some(12.0)
				&& built.version == 1
				&& !built.deprecated
				&& matches!(unknown_param, LibraryError::UnknownParam { .. })
				&& unknown_param.to_string().contains("'hh'")
				&& matches!(out_of_range, LibraryError::OutOfRange { .. })
				&& out_of_range.to_string().contains("[4, 40]")
				&& matches!(nan, LibraryError::OutOfRange { .. })
				&& matches!(unknown_part, LibraryError::UnknownPart { .. })
				&& unknown_part.to_string().contains("bushing")
				&& matches!(unknown_version, LibraryError::UnknownVersion { .. })
				&& unknown_version.to_string().contains("v1")
				&& deprecated_count == 1
				&& hidden.is_empty()
				&& warned.deprecated
				&& volume > 0.0,
			"instantiate semantics: h={h:?} outer_r={outer_r:?} unknown_param={unknown_param} out_of_range={out_of_range} nan={nan} unknown_part={unknown_part} unknown_version={unknown_version} deprecated_count={deprecated_count} hidden={} warned={} volume={volume}",
			hidden.len(),
			warned.deprecated
		);
		let _ = std::fs::remove_dir_all(&dir);
	}

	/// Removal honors dependents: an `.lmcasm` in the directory referencing the
	/// stored part by path (even via `./`) blocks `remove` with the dependent's
	/// name; `force` removes anyway; the files and index rows are gone after.
	/// A second-version add then proves versions resolve (latest by default).
	#[test]
	fn remove_refuses_dependents_unless_forced_and_versions_resolve() {
		let dir = test_dir("remove");
		let mut lib = Library::open(&dir).expect("open");
		lib.add(&bushing_part_json(), bushing_meta(), &AddOptions::default()).expect("admit v1");
		let mut v2 = bushing_meta();
		v2.version = 2;
		v2.param_interface[2].max = 60.0; // v2 widens the height range
		lib.add(&bushing_part_json(), v2, &AddOptions::default()).expect("admit v2");

		// A hand-written assembly referencing v1 by (dot-prefixed) path.
		let asm = r#"{
			"format": "lmc-asm", "version": 1, "units": "mm", "name": "stack",
			"instances": [{"source": {"path": "./bushing-v1.lmcpart"}, "pose": {"translation": [0.0, 0.0, 0.0]}}],
			"mates": []
		}"#;
		std::fs::write(dir.join("stack.lmcasm"), asm).expect("write asm");

		let latest = lib.entry("bushing", None).expect("latest").version;
		let refused = lib.remove("bushing", false).expect_err("dependent must block");
		let removed = lib.remove("bushing", true).expect("force removes");
		let gone = lib.entry("bushing", None).expect_err("no entries left");
		assert!(
			latest == 2
				&& matches!(&refused, LibraryError::DependentsExist { dependents, .. } if dependents == &vec!["stack.lmcasm".to_string()])
				&& refused.to_string().contains("stack.lmcasm")
				&& removed == ["bushing-v1.lmcpart", "bushing-v2.lmcpart"]
				&& !dir.join("bushing-v1.lmcpart").exists()
				&& !dir.join("bushing-v2.lmcpart").exists()
				&& matches!(gone, LibraryError::UnknownPart { .. }),
			"curation: latest={latest} refused={refused} removed={removed:?} gone={gone}"
		);
		let _ = std::fs::remove_dir_all(&dir);
	}

	/// The corner plan is deterministic and honest about its cap: n ≤ 4 is
	/// exhaustive (2ⁿ), n = 6 under the default cap of 16 keeps all-min,
	/// all-max and every single-parameter extreme, and two runs agree exactly.
	#[test]
	fn corner_plan_is_deterministic_and_capped() {
		let exhaustive = corner_masks(3, 16);
		let capped = corner_masks(6, 16);
		let again = corner_masks(6, 16);
		let one_hot_coverage = (0..6).all(|j| {
			capped.iter().any(|m| m[j] && m.iter().filter(|&&b| b).count() == 1)
				&& capped.iter().any(|m| !m[j] && m.iter().filter(|&&b| !b).count() == 1)
		});
		assert!(
			exhaustive.len() == 8
				&& capped.len() == 16
				&& capped[0] == vec![false; 6]
				&& capped[1] == vec![true; 6]
				&& one_hot_coverage
				&& capped == again,
			"corner plan: exhaustive={} capped={} one_hot_coverage={one_hot_coverage} deterministic={}",
			exhaustive.len(),
			capped.len(),
			capped == again
		);
	}
}
