#!/usr/bin/env python3
"""fea_report.py — run a campaign's FEA jobs and regenerate the receipts
table inside its FEA.md, so no number in the report is ever hand-pasted.

Usage:  python3 tools/fea_report.py <campaign_fea_dir>
Expects <dir>/manifest.json:
    {"python": "/path/to/ace/python3",          # optional, else sys default
     "cases": [{"name": "...", "vox": "vox_a.json", "fea": "fea_a.json"}]}
Reads each case's runner receipt (last stdout line JSON) and rewrites the
block between the markers in <dir>/FEA.md:
    <!-- fea-receipts:begin -->  ...  <!-- fea-receipts:end -->
Interpretation prose outside the markers is untouched. Receipt (last stdout
line): {"ok": true, "cases": N, "md": path}.
"""
import json, os, subprocess, sys

def main():
	d = sys.argv[1]
	man = json.load(open(os.path.join(d, "manifest.json")))
	py = man.get("python", sys.executable)
	root = os.getcwd()
	rows = []
	for case in man["cases"]:
		for step in ("vox", "fea"):
			job = os.path.join(d, case[step])
			tool = "tools/voxelize_stl.py" if step == "vox" else "tools/ace_fea_runner.py"
			out = subprocess.run([py, tool, job], capture_output=True, text=True, cwd=root)
			last = [l for l in out.stdout.strip().splitlines() if l.strip()][-1]
			rec = json.loads(last)
			if not rec.get("ok"):
				print(json.dumps({"ok": False, "case": case["name"], "step": step, "error": rec}))
				return 1
		conv = rec.get("residual_or_convergence", {})
		rows.append(
			f"| {case['name']} | {rec['max_von_mises_pa']/1e6:.2f} MPa | "
			f"{rec['max_displacement_m']*1e3:.3f} mm | {rec['n_active_elements']} / {rec['n_dof']} | "
			f"converged={conv.get('converged')} rtol={conv.get('target_rtol')} | {rec['timings_s']['fea_s']:.0f} s |"
		)
	table = (
		"<!-- fea-receipts:begin (regenerated by tools/fea_report.py — do not hand-edit) -->\n"
		"| case | peak von Mises | max displacement | elements / DOF | convergence | solve |\n"
		"|---|---|---|---|---|---|\n" + "\n".join(rows) + "\n<!-- fea-receipts:end -->"
	)
	md_path = os.path.join(d, "FEA.md")
	md = open(md_path).read()
	b, e = md.find("<!-- fea-receipts:begin"), md.find("<!-- fea-receipts:end -->")
	if b == -1:
		md = md.rstrip() + "\n\n## Receipts (machine-generated)\n\n" + table + "\n"
	else:
		md = md[:b] + table + md[e + len("<!-- fea-receipts:end -->"):]
	open(md_path, "w").write(md)
	print(json.dumps({"ok": True, "cases": len(rows), "md": md_path}))
	return 0

if __name__ == "__main__":
	sys.exit(main())
